<a href="https://colab.research.google.com/github/hebatoallah-yehya1111/Big_Data_Task/blob/main/Big_Data_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Consumption

This included :

1) reading the csv 


2) Handling malformed records

In [1]:
import pandas as pd
import csv
import os


# Set up file paths
csv_file_path = "MetObjects.csv"
output_dir = "/content"
malformed_records_file_path = os.path.join(output_dir, "malformed_records.csv")
malformed_records_list=[]
# Read the CSV file and handle malformed records
try:
    df = pd.read_csv(csv_file_path)
except pd.errors.ParserError as e:
    # Handle the ParserError and store the malformed records
    malformed_records = e.args[0].split('\n')
    malformed_records_list.append[malformed_records]

    
    # Write the malformed records to a separate file
with open(malformed_records_file_path, 'w') as file:
             for record in  malformed_records_list :
              file.write(record + '\n') 
    
    # Continue reading the remaining valid records
df = pd.read_csv(csv_file_path, error_bad_lines=False, warn_bad_lines=True)

<ipython-input-1-7508e43224e6>:13: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path)
<ipython-input-1-7508e43224e6>:26: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(csv_file_path, error_bad_lines=False, warn_bad_lines=True)
<ipython-input-1-7508e43224e6>:26: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(csv_file_path, error_bad_lines=False, warn_bad_lines=True)
<ipython-input-1-7508e43224e6>:26: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path, error_bad_lines=False, warn_bad_lines=True)

Check that csv is read propably

In [2]:
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477799,23.112.2893,False,False,True,860869,NaN,Drawings and Prints,1923,Drawing,Phaeton #24567,...,NaN,Drawings,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356
477800,23.112.2894,False,False,True,860870,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton #25538-25539 (#21222),...,NaN,Drawings,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356
477801,53.600.1434,False,False,False,860871,NaN,Drawings and Prints,1953,Print,"Forest landscape with cattle drinking, a woman...",...,NaN,Prints,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
477802,23.112.2895,False,False,True,860872,NaN,Drawings and Prints,1923,Drawing,Phaeton with folding top,...,NaN,Drawings,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356
477803,23.112.2896,False,False,True,860873,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton,...,NaN,Drawings,NaN,http://www.metmuseum.org/art/collection/search...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356

Check names of Columns

In [3]:
df.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 477804 entries, 0 to 477803
Data columns (total 54 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Object Number            477804 non-null  object
 1   Is Highlight             477804 non-null  bool
 2   Is Timeline Work         477804 non-null  bool
 3   Is Public Domain         477804 non-null  bool
 4   Object ID                477804 non-null  int64
 5   Gallery Number           51776 non-null   object
 6   Department               477804 non-null  object
 7   AccessionYear            474248 non-null  object
 8   Object Name              476113 non-null  object
 9   Title                    448619 non-null  object
 10  Culture                  207379 non-null  object
 11  Period                   90956 non-null   object
 12  Dynasty                  23233 non-null   object
 13  Reign                    11226 non-null   object
 14  Portfolio                23530 non-null   object
 15  Constituent ID           275535 non-null  object
 16  Artist Role              273436 non-null  object
 17  Artist Prefix            275535 non-null  object
 18  Artist Display Name      275535 non-null  object
 19  Artist Display Bio       273436 non-null  object
 20  Artist Suffix            275487 non-null  object
 21  Artist Alpha Sort        275535 non-null  object
 22  Artist Nationality       275535 non-null  object
 23  Artist Begin Date        275535 non-null  object
 24  Artist End Date          275535 non-null  object
 25  Artist Gender            103061 non-null  object
 26  Artist ULAN URL          222021 non-null  object
 27  Artist Wikidata URL      217732 non-null  object
 28  Object Date              463937 non-null  object
 29  Object Begin Date        477804 non-null  int64
 30  Object End Date          477804 non-null  int64
 31  Medium                   470684 non-null  object
 32  Dimensions               402510 non-null  object
 33  Credit Line              477353 non-null  object
 34  Geography Type           59769 non-null   object
 35  City                     32407 non-null   object
 36  State                    2550 non-null    object
 37  County                   8450 non-null    object
 38  Country                  75751 non-null   object
 39  Region                   31360 non-null   object
 40  Subregion                22124 non-null   object
 41  Locale                   15709 non-null   object
 42  Locus                    7493 non-null    object
 43  Excavation               16558 non-null   object
 44  River                    2095 non-null    object
 45  Classification           399598 non-null  object
 46  Rights and Reproduction  24198 non-null   object
 47  Link Resource            477804 non-null  object
 48  Object Wikidata URL      22265 non-null   object
 49  Metadata Date            0 non-null       float64
 50  Repository               477804 non-null  object
 51  Tags                     200400 non-null  object
 52  Tags AAT URL             200400 non-null  object
 53  Tags Wikidata URL        200400 non-null  object
dtypes: bool(3), float64(1), int64(3), object(47)
memory usage: 187.3+ MB

#Pre-Processing

###a) Dimensions column

In [5]:
#Show Dim Column to see its  structure
df['Dimensions']

0                              Dimensions unavailable
1                              Dimensions unavailable
2                            Diam. 11/16 in. (1.7 cm)
3                            Diam. 11/16 in. (1.7 cm)
4                            Diam. 11/16 in. (1.7 cm)
                             ...
477799    Sheet: 13 1/2 × 22 1/2 in. (34.3 × 57.2 cm)
477800      Sheet: 13 in. × 22 1/4 in. (33 × 56.5 cm)
477801     Plate: 11 5/8 × 7 5/8 in. (29.6 × 19.4 cm)
477802      Sheet: 13 in. × 22 1/4 in. (33 × 56.5 cm)
477803    Sheet: 11 3/4 × 17 3/4 in. (29.8 × 45.1 cm)
Name: Dimensions, Length: 477804, dtype: object

In [6]:
#Remove Dims in inches and remain only cm 
df["New_Dimensions"] = df["Dimensions"].str.extract(r"\((.*?)\)" , expand=False)
df["New_Dimensions"]

0                    NaN
1                    NaN
2                 1.7 cm
3                 1.7 cm
4                 1.7 cm
               ...
477799    34.3 × 57.2 cm
477800      33 × 56.5 cm
477801    29.6 × 19.4 cm
477802      33 × 56.5 cm
477803    29.8 × 45.1 cm
Name: New_Dimensions, Length: 477804, dtype: object

In [7]:
#Remove word cm
df['New_Dimensions'] = df['New_Dimensions'].str.replace('cm','')
df['New_Dimensions']

0                  NaN
1                  NaN
2                 1.7
3                 1.7
4                 1.7
              ...
477799    34.3 × 57.2
477800      33 × 56.5
477801    29.6 × 19.4
477802      33 × 56.5
477803    29.8 × 45.1
Name: New_Dimensions, Length: 477804, dtype: object

In [21]:
#Function to clean the dim column 
def clean_Dim(dim):
    if isinstance(dim, str):
        dim = dim.strip()  # Remove leading/trailing whitespaces
        dim = dim.replace(' x ', ' ')  
        dim = dim.replace(' H.', ' ')  
        dim = dim.replace(' dwt ', '')  
        dim = dim.replace('Diam. ', '') 

    return dim

In [22]:
df['New_Dimensions'] = df['New_Dimensions'].apply(clean_Dim)

In [23]:
df['New_Dimensions'].unique().tolist()

[nan,
 '1.7',
 '1.3',
 '2.9',
 '1.9',
 '5.4',
 '7 8.9 7',
 '61.9 37.1 13',
 '49.4 33 23.5',
 '101.6 64.8 87.6',
 '30.5',
 '31.4',
 '27.9 22.9',
 '16.7',
 '15.9',
 '78.4 63.5 35.2',
 '68.6',
 '40.6',
 '43.2',
 '29.2',
 '41.9',
 '58.4',
 '57.2 58.4',
 '64.1 54.6 34.3',
 '59.7',
 '47 56.5 34.3',
 '53.3 53.3 34.3',
 '78.1 71.1',
 '54 45.1',
 '45.1 61',
 '64.8 56.5 34.3',
 '41 38.7 20.6',
 '48.9 49.5 29.8',
 '52.7 49.5 29.8',
 '47.6 43.2',
 '59.1 59.7',
 '53.3 40',
 '59.1 46.4',
 '28.9 36.8 30.5',
 '47.6 44.5 27.3',
 '57.2 68.6 33',
 '61 29.2 40.6',
 '57.2',
 '41 25.4 37.8',
 '47 43.2',
 '62.2 × 33 × 51.8',
 '53.7',
 '80 35.6 59.7',
 '63.5 38.1 88.9',
 '57.5 27.3 52.1',
 '9.2',
 '7',
 '109.2',
 '210.8 148.6',
 '640.1 701',
 '44.5',
 '45.4 43.2 20',
 '86.4 59.7 48.3',
 '101.6 63.5 44.5',
 '111.8 61 38.1',
 '113 58.4 57.2',
 '121.9 74.9 42.9',
 '14 21.6',
 '106.7 61 38.4',
 '119.4 66 61',
 '116.8 55.9 53.3',
 '109.2 63.5 38.1',
 '97.2 64.8 38.1',
 '127.6 59.7 43.2',
 '116.8 59.7 43.2',
 '115.6 57.8 55.9',
 '117.5 63.2 44.8',
 '99.1 58.4 47',
 '99.7 62.9 58.4',
 '123.8 62.2 43.2',
 '82.6 54.3 57.9',
 '111.8 84.5 54.6',
 '108 82.6 53.3',
 '104.1 80 54',
 '81.9 47 54.6',
 '106.4 67.9 40.6',
 '128.3 63.5 40',
 '94.9 55.9 43.2',
 '98.4 54.6 45.7',
 '99.4 53 55.9',
 '109.2 61 49.5',
 '107 68.6 71.1',
 '100.3 61 43.2',
 '13.3 12.1',
 '71.1 68.6 43.2',
 '91.4 57.2 48.9',
 '89.2 61.9 36.2',
 '113.7 59.7 40',
 '114.9 62.9 45.1',
 '106 58.4 45.7',
 '103.2 68.6 43.2',
 '97.8 54.9 42.2',
 '28.6 25.2',
 '90.2 66 55.9',
 '123.8 62.9 53.3',
 '91.4 52.1 48.3',
 '98.4 67.9 88.9',
 '100.3 76.2 59.7',
 '103.5 61.6 48.3',
 '163.8 64.5 56.5',
 '92.1 61 49.5',
 '109.2 71.8 76.2',
 '90.2 57.2 49.5',
 '80 51.8 64.8',
 '109.9 64.8 46.4',
 '87.9 63.5 67.9',
 '110.5 70.2 52.7',
 '114.3 52.7 68.6',
 '97.8 66 83.8',
 '86.4 52.7 56.5',
 '150.5 83.8 67',
 '103.5 64.8 50.8',
 '102.9 66 62.9',
 '116.2 73.7 69.9',
 '82.6 53.3 45.7',
 '134.6 58.4 55.9',
 '89.5 53.3 48.3',
 '83.5 56.2 48.3',
 '84.5 61 50.8',
 '123.8 64.8 58.4',
 '131.4 71.1 63.5',
 '94 69.9 69.9',
 '83.8 63.5 73.7',
 '90.5 64.1 66.4',
 '89.9 65.1 66.7',
 '96.5 52.7 62.9',
 '92.7 61 60.3',
 '113 72.4 74.6',
 '121.9 69.9 78.7',
 '91.4 57.8 52.7',
 '96.5 57.5 43.5',
 '95.9 56.5 46.4',
 '97.2 57.8 44.1',
 '93.3 58.4 45.7',
 '127 67.3 58.4',
 '125.7 67.3 57.2',
 '85.7 53.7 53.3',
 '85.7 53.7 54.3',
 '97.8 59.1 66.4',
 '83.5 54.6 62.9',
 '83.2 53 45.1',
 '96.5 54 64.8',
 '96.5 54 64.3',
 '68.6 45.7 38.7',
 '117.8 62.9 65.4',
 '84.5 94 73.7',
 '54.6 24.8',
 '66.7',
 '335.3 259.1',
 '74.9',
 '11.1 16.5 7.9',
 '16.5',
 '6.4',
 '5.1',
 '4.4',
 '4.1',
 '3.3',
 '12.4 10.8',
 '7.3',
 '9.5',
 '113 614.7',
 '20.3',
 '19.1',
 '99.1 25.1 2.5',
 '101.6 25.1 5.4',
 '27.6 80.6',
 '80.6 27.6 2.9',
 '87.6 25.4',
 '24',
 '23.5',
 '23.2',
 '102.9 25.4',
 '26',
 '42.5',
 '5.7',
 '24.8 28.9',
 '6 2.2',
 '6.4 1.9',
 '27.6',
 '14.6 15.2 11.7',
 '10.5 11.7 9.2',
 '52.1 26.7',
 '28.6',
 '15.2',
 '10.8',
 '34.3',
 '4.4 20.3 20.3',
 '4.1 16.8 16.8',
 '5.1 14.6 14.6',
 '6.7',
 '12.1',
 '11.1',
 '34.9',
 '33',
 '7 32.7 32.7',
 '85.7 45.7 45.7',
 '105.4 55.9 40.6',
 '66 48.3 48.3',
 '6 11.7',
 '11.3 13.3 18.6',
 '14.9 24.8 24.8',
 '31.1 49.5 36.2',
 '43.2 35.6',
 '47 34.3',
 '26.7',
 '28.4 36.7 28.9',
 '11.4 15.9',
 '182.9 82.6',
 '188 78.7',
 '16.8',
 '8.6',
 '29.8',
 '18.4',
 '6.2',
 '8.7',
 '17.8',
 '18.3',
 '13',
 '14',
 '7.9',
 '8.1',
 '8.9',
 '7.6',
 '15.1',
 '13.7',
 '9',
 '7.5',
 '8.4',
 '11.4',
 '12.6',
 '9.8',
 '13.3',
 '7.8',
 '18.1',
 '17.1 × 10.2 × 10.2',
 '10.3',
 '10.2',
 '24.1',
 '22.2',
 '196.9 134 193',
 '223.8 155.6 195.6',
 '251.8 167.6 214.6',
 '245.1 142.9 196.2',
 '81.3 120.7 179.1',
 '205.7 134.3 195.6',
 '180.3 76.2 78.7',
 '299.7 176.5 227.3',
 '271.1 148.9 201.9',
 '161 99.1 205.7',
 '130.8 125.1 42.5',
 '12.4',
 '35.6',
 '17.8 × 10.2',
 '50.8',
 '53.3 21.6',
 '44 18.6',
 '44.5 85.1 35.6',
 '50.2 180.3 33',
 '52.7 77.5 27.3',
 '67.3 238.8 30.5',
 '42.2 90.2 24.1',
 '60.3 60.6 48.9',
 '44.5 69.9 42.4',
 '97.8 84.5 48.3',
 '87.6 140.7 52.7',
 '37.5',
 '8.3 6.7',
 '6 5.1',
 '9.8 7.3',
 '7.6 6',
 '6.7 5.1',
 '25.4 14.3 11.7',
 '12.7',
 '4.8',
 '18.4 14.6',
 '14.3 8.9',
 '13.7 10.2',
 '14.6 10.8',
 '13.7 10.8',
 '34 27.6',
 '10.8 10.5',
 '14.3',
 '14.9',
 '15.6',
 '28.6 23.5',
 '10.3 7.6',
 '14.6 9.8',
 '29.8 25.4',
 '16.2 13.3',
 '91.4 45.1 55.9',
 '20.3 6.4',
 '25.4',
 '29.2 11.4',
 '20.3 10.2',
 '15.2 8.9 5.1',
 '43.5 28.6',
 '42.5 26',
 '34.6 22.9',
 '35.6 24.1',
 '18.1 8.7 8.7',
 '13.3 8.3',
 '31.8 43.2 31.1',
 '35.2 42.9',
 '43.2 34.3',
 '31.1 37.5',
 '31.1 41.9',
 '31.8 36.8',
 '31.4 39.7',
 '34.3 41.3',
 '32.9 40.5',
 '33.7 40',
 '34.3 43.2',
 '32.1 40',
 '33.7 41.3',
 '30.5 39.4',
 '21.9 34.9',
 '29.2 22.9',
 '30.5 38.4',
 '21.6',
 '113 116.8 63.5',
 '126.4 113 62.2',
 '4.9 14.8 7.6',
 '46.4 30.8',
 '48.4',
 '10 1.7',
 '26.7 20.3',
 '19.4 14.3',
 '27.3',
 '43.5',
 '231.8 124.5 69.5',
 '242.6 152.4 55.9',
 '242.6 152.4 54.6',
 '16.5 17.8',
 '5.4 15.2 1',
 '5.6 15.6 1',
 '5.6 15.7 1.1',
 '5.6 15.6 1.1',
 '5.5 15.6 1',
 '5.4 15.2 0.8',
 '15.6 5.6 1',
 '15.6 5.4 1',
 '15.6 5.6 0.8',
 '15.7 5.6 1',
 '15.4 5.4 1',
 '47',
 '53.3',
 '30.8',
 '14.6',
 '15.6 6.4',
 '21.3',
 '18.7',
 '17.1',
 '6',
 '25.1',
 '20.6',
 '10.5',
 '11',
 '22.9',
 '11.7',
 '28.9 5.2',
 '7.6 7',
 '2.5',
 '3.5 2.9',
 '19.7 , 7.073 Troy Ounces',
 '19.1 , 7.192 Troy Ounces',
 '18.9 , 5.916 Troy Ounces',
 '19.2 , 6.687 Troy Ounces',
 '11.7 , 3.431 Troy Ounces',
 '11.3 , 4.215 Troy Ounces',
 '13.3 38.1 34.9',
 '40.3',
 '19.4',
 '33.7',
 '52.7',
 '24.8',
 '8.3',
 '6.7 14.9',
 '2.7 10.8',
 '10.4',
 '61',
 '7.9 15.9',
 '7 13.3',
 '11.1 25.2',
 '20',
 '21',
 '16.2',
 '20.5',
 '25.2',
 '30.3',
 '26.8',
 '23.7',
 '27.9',
 '30.6',
 '23.0  Diam.',
 '23.8',
 '22.4',
 '26.5',
 '8.6 24.8 48.9',
 '10.2 21.7',
 '8.6 20.6',
 '23.3',
 '13.2',
 '12.7 26.7',
 '12.1 25.7',
 '5.7 12.1',
 '7.6 18.1',
 '13.7 35.1',
 '12.5 30.3',
 '7.6 32.5 11',
 '10',
 '6.4 13.7 13.7',
 '20.2',
 '14.1',
 '13.3 24.4',
 '7.3 11',
 '16',
 '15.6 24.1 24.1',
 '5.7 9.4 9.4',
 '3.8 5.1 5.1',
 '9.8 16.5',
 '12.9 28.6',
 '8.3 38.4 21.9',
 '6.4 13.7',
 '12.9',
 '5.9 24.9 20.2',
 '14.3 17.8',
 '4.3',
 '4.1 6 6',
 '3.2 8.9 8.9',
 '2.2 8.9',
 '2.5 7.8',
 '1.9 7.3',
 '2.2 7.3',
 '2.2 8.1 8.1',
 '2.5 7.8 7.8',
 '1.6 6.7 6.7',
 '1.9 8.3 8.3',
 '22.9 67.3 38.1',
 '22.9 67.3 40.6',
 '17.8 66.7 43.2',
 '20.3 68.6 45.4',
 '24.1 74.9 40.6',
 '22.9 74.9 43.8',
 '5.7 11.7 6.4',
 '1 7.6 2.5',
 '12.1 13.1 10.8',
 '7.6 12.7 7.3',
 '10.8 21.9 14.6',
 '17.1 32.7 24.8',
 '28.6 74.3 33.7',
 '17.1 58.1 40.6',
 '36.8 14 13.3',
 '6.4 4.8 8.6',
 '10.8 17.5 12.1',
 '8.6 12.7 8.6',
 '8.9 15.2 8.9',
 '6.7 13 7',
 '8.3 10.2 7.3',
 '6.4 8.6 6.7',
 '4.4 9.2 5.7',
 '5.7 9.5 5.7',
 '5.4 10.2 7.3',
 '12.1 63.5 34.9',
 '17.8 53.3 33.7',
 '19.4 41 22.9',
 '2.5 3 4.3',
 '6.4 20.6 21.6',
 '6.4 19.1 12.7',
 '24.1 71.8 47',
 '6.4 3.8',
 '3.8 7.9',
 '26 72.4 36.2',
 '24.1 67.6 39.4',
 '3.8 11.7 7',
 '11.4 10.2',
 '16.5 8.4 6',
 '20.3 20.3',
 '4.9 7.6 2.5',
 '5.7 13 8.9',
 '3.2 13.2',
 '24.1 6.7',
 '11.4 22.9',
 '48.3 31.1 20.3',
 '13.7 7.6',
 '65.4 15.2',
 '15.9 41.9',
 '20.6 10.5 5.4',
 '19.1 47.6 29.8',
 '16.5 43.2 27.6',
 '17.8 43.8 27.3',
 '16.5 43.5 27.6',
 '13.3 33 18.7',
 '21 48.7 30.5',
 '3.3 4.4',
 '5.4 8.9',
 '3.2 4.4',
 '2.9 6',
 '1.7 6.2 6.7',
 '85.1 35.6 28.7',
 '0.8 3.2 2.9',
 '1.3 8.6 6',
 '15.2 20.3',
 '22.5 9.8',
 '76.2 98.7 57.5',
 '80.6 90.2 52.7',
 '83.8 89.2 56.8',
 '87.3 92.7 52.1',
 '11.6',
 '11.9 14.3',
 '18.7 12.1 11.4',
 '7.9 5.7',
 '4.8 2.2',
 '2.9 2.5',
 '3.5',
 '2.4',
 '2.2',
 '45.7 43.2 25.4',
 '199.4 134.6 48.9',
 '205.7 168.3 50.8',
 '90.5 73.7 45.7',
 '112.4 81.3 48.9',
 '108.9 183.4 54',
 '243.8 106.7 50.8',
 '135.6 186.4 46.7',
 '210.2 154.9 47',
 '16.7 24.8',
 '16.7 24.4',
 '12.2',
 '19.7',
 '21.6 29.4',
 '16.5 19.4',
 '55.9 12.4',
 '3 2.2',
 '3.8 4.8',
 '9.2 7',
 '5.7 4.8',
 '10.8 8.3',
 '10.2 7.9',
 '10.2 7.8',
 '1.9 3.8',
 '70.8',
 '73.7',
 '37.8 67.3',
 '67.3',
 '50.2',
 '70.5',
 '82.6',
 '45.1 44.5 10.2',
 '55.2',
 '71.1',
 '62.9',
 '62.2',
 '52.1',
 '78.6',
 '17.5 13.7 10.3',
 '58.1 51.3',
 '50.5 41',
 '50.2 41.3',
 '29.2 23.5',
 '50.2 38.7',
 '49.5 40',
 'a',
 '16.5 38.1 24.1',
 '14.3 30.5 15.9',
 '12.9 24.4 12.1',
 '54.6',
 '72.4 44.5 44.5',
 '165.1',
 '172.7',
 '81.3 35.6',
 '74.3 42.5 42.5',
 '72.4',
 '114.3',
 '157.5',
 '68.6 36.8 29.5',
 '70.5 50.2 36.8',
 '94.9',
 '66 47.6 32.1',
 '64.8 45.7 45.7',
 '41.3 33.7 16.4',
 '108.6 27 26.4',
 '74.3',
 '72.4 26 43.2',
 '155.9 39.4 40.6',
 '127 33',
 '39.4',
 '25.4 12.7 12.7',
 '24.9',
 '6.4 13.3 16.5',
 '28.9 10.2 10.2',
 '26.4',
 '17.6',
 '22.7',
 '17.9',
 '13.2 15.4',
 '29.1 16.5 16.5',
 '29.8 16.4 16.4',
 '34.3 42.9',
 '5.2',
 '24.4',
 '42.9 12.1 8.6',
 '21.9',
 '27.8',
 '30.6 15.6 12.7',
 '21.9 12.2',
 '34.1 9.8',
 '34.1 9.5',
 '20 13 13',
 '17.1 10.2',
 '17.8 10.2',
 '23.7 × 11.9 × 11.9',
 '15.4 10',
 '15.6 10.2',
 '25.9 14',
 '25.2 12.9',
 '36.8 17.5',
 '28.1',
 '45.1',
 '31.1',
 '16 8.7 8.4',
 '16 8.6 8.4',
 '47.6',
 '28.3',
 '28.36',
 '29.4 15.7',
 '55.9',
 '49.5',
 '33.3',
 '18.4 13.3',
 '17.5',
 '17',
 '142.2',
 '16.7 16.5',
 '16.5 16.2',
 '31.8 20',
 '8.9 20.3 27.9',
 '30.5 36.8 45.7',
 '88.3 82.2 10.2',
 '10.2 5.1',
 '9.5 5.4',
 '72.4 90.8',
 '91.4 144.8',
 '73 88.9 86.4',
 '76.2 88.9',
 '71.8 86.4 90.8',
 '72.4 87.6 40.6',
 '73.7 91.4 45.7',
 '72.7 88.9 85.4',
 '73.3 94 96.5',
 '70.8 88.9 45.1',
 '70.5 84.5 41.9',
 '78.1 91.4 44.9',
 '78.1 88.9 43.8',
 '69.2 90.2 87.6',
 '70.8  87.3  84.5',
 '74.3 91.4 48.9',
 '67.9 × 88.9 × 40.6',
 '73 92.4 91.1',
 '73.3 91.4 44.5',
 '69.2 90.5',
 '74.9 80 47',
 '76.2 89.5 44.5',
 '71.1 94 47',
 '78.7 90.6 45.1',
 '72.4 91.4',
 '69.2 86 42.9',
 '72.4 91.4 83.8',
 '74.9 91.4 45.7',
 '71.8 90.5',
 '15.6 8.3 6.7',
 '76.8 64.8',
 '60.3 51.4',
 '62.9 42.5',
 '43.2 42.5',
 '14.3 5.1',
 '17.5 5.2',
 '9.7 5.7',
 '13.2 4.4',
 '17.3 7',
 '13.8',
 '13.3 4.8',
 '9.5 4.9',
 '9.5 7.9',
 '17.6 6.7',
 '12.4 6.8',
 '9 5.9',
 '12.7 4.9',
 '17.5 6.4',
 '14 4.9',
 '14.3 4.9',
 '45.4 45.4',
 '3.7 2.9',
 '7.6 16.5',
 '18.9',
 '19.5',
 '18.6',
 '45.7',
 '45.6',
 '62.2 68.6 52.1',
 '55.9 68.6 50.8',
 '32.4 26',
 '72.4 84.8 84.8',
 '65.7',
 '79.4 119.4 78.7',
 '75.7',
 '32.4',
 '11.9 31.8 18.1',
 '8.6 16.2',
 '9.7 25.7',
 '66',
 '93.3 58.4 53.3',
 '114.3 47 39.4',
 '96.5 48.3 40.6',
 '133.4 45.7 36.8',
 '96.5 45.7 36.8',
 '119.4 43.2 37.5',
 '125.7 45.7 38.1',
 '105.4 48.9 41',
 '117.5 44.5 33',
 '13.7 13.2',
 '115.6 67.3 41.9',
 '104.5 52.1 43.2',
 '21.6 14',
 '94 57.8 47',
 '86.4 50.8 48.3',
 '95.3 50.2 36.8',
 '101 50.2 35.6',
 '98.4 53 44.5',
 '83.8 47 41.3',
 '88.9 47 39.4',
 '104.8 55.2 54',
 '104.1 55.9 53.3',
 '105.4 52.7 50.8',
 '106.7 54 52.1',
 '107.3 53.3 49.5',
 '101.6 52.1 47',
 '108.6 51.1 52.1',
 '101.6 53 52.1',
 '106.7 51.4 41.9',
 '101.6 49.8 50.2',
 '101 55.9 44.5',
 '116.5 45.7 37.5',
 '106 57.5 57.2',
 '99.1 54.6 54.6',
 '98.4 56.8 54.6',
 '96.8 56.5 56.5',
 '101 47 38.7',
 '83.2 48.3 38.7',
 '12.7 11.4',
 '87.6 53.3 45.7',
 '97.8 53.3 45.7',
 '97.8 53.3 44.5',
 '97.2 56.5 52.7',
 '105.4 47 36.8',
 '96.5 60.3 55.9',
 '134 47.6 38.1',
 '96.2 55.9 51.4',
 '97.2 55.9 57.2',
 '117.5 44.5 36.8',
 '93.3 52.7 45.7',
 '101.3 50.2 49.2',
 '96.5 55.6 54.6',
 '103.5 53.3 43.2',
 '94 52.1 44.5',
 '121.9 45.7 38.1',
 '92.7 52.1 45.7',
 '98.1 52.1 44.5',
 '96.5 48.3 45.1',
 '102.9 55.9 55.2',
 '101.6 55.2 54.6',
 '106.7 43.8 51.1',
 '58.7 46.4 54',
 '108 47.6 52.7',
 '96.2 56.5 53.3',
 '86.4 41.9 41.9',
 '74.9 54 57.2',
 '98.4 54 52.1',
 '93 45.1 46.4',
 '99.1 54.9 55.9',
 '94.6 59.7 55.2',
 '96.8 55.6 52.1',
 '89.5 52.7 49.5',
 '87.6 36.2 45.4',
 '73.7 36.8 45.7',
 '90.2 40.3 43.2',
 '101 53.3 54.3',
 '98.1 55.9 54.6',
 '98.7 53.7 54.6',
 '85.1 44.5 53.3',
 '86.7 42.5 42.5',
 '105.4 52.4 39.4',
 '97.8 58.4 59.7',
 '105.1 54.6 57.8',
 '110.5 47 39.4',
 '82.1 49.5 54.6',
 '96.8 57.8 52.1',
 '26 54 50.8',
 '51.4 54.6',
 '94 57.2 58.4',
 '99.7 56.8 56.5',
 '96.5 53.3 48.3',
 '106.7 37.1 45.7',
 '88.9 46.4 41.9',
 '106.7 47 54.6',
 '74.9 59.7',
 '95.9 50.2 52.7',
 '100.6 50.5 41.3',
 '86 46.4 66',
 '80 39.1 48.9',
 '94 55.9',
 '96.2 70.8 45.7',
 '82.2 47.1 53.3',
 '83.8 46.7 52.1',
 '83.2 44 46.2',
 '81.6 44.8 47',
 '81.9 55.2 46.7',
 '84.5 48.6 41.9',
 '71.4 63.5 55.2',
 '94.3 45.7 45.7',
 '80.6 42.5 48.9',
 '91.4 52.1 40.6',
 '79.1 45.1',
 '91.4 59.7 45.7',
 '141.6 43.2 47',
 '88.9 35.6 43.2',
 '101.9 38.1 47.9',
 '71.1 53.3 71.1',
 '89.5 25.4 25.4',
 '88.9 49.5 50.8',
 '86 43.2 39.4',
 '97.8 55.9 67.9',
 '108.6 50.8 50.2',
 '102.9 55.2 54',
 '87 49.5 43.2',
 '113 45.7 38.1',
 '98.4 60 53.3',
 '98.4 54.9 44.5',
 '98.7 53.3 54.6',
 '97.8 56.5 55.9',
 '97.8 55.9 52.1',
 '96.5 54.6 48.3',
 '97.8 54.6 47',
 '120.7 53.3 40',
 '98.4 54.6 45.1',
 '100.3 48.3 47',
 '100.3 47 47.6',
 '98.7 61.6 56.5',
 '99.7 54.3 54',
 '96.4 47.1 39.4',
 '97.2 47.3 40',
 '104.8 48.3 50.8',
 '87.9 44.1 46.7',
 '87.9 43.8 46.7',
 '86.4 43.2 49.5',
 '99.7 54 52.7',
 '84.8 45.1 46.7',
 '82.2 45.1 48.9',
 '93.3 50.8 50.8',
 '84.5 48.9 54',
 '126.4 46.7 53.7',
 '126.4 47.6 53.7',
 '85.1 52.7 42.5',
 '114 55.9 43.2',
 '87.6 45.4 48.3',
 '88.3 45.4 48.3',
 '82.6 50.2 50.8',
 '94.5 53.3 49.5',
 '90.8 53.3 44.5',
 '100.3 54 45.7',
 '103.5 63.5 48.9',
 '83.8 45.7 48.3',
 '83.2 47 43.2',
 '83.2 43.2 49.8',
 '83.2 43.2 49.5',
 '91.4 57.2 45.7',
 '103.8 52.7 45.1',
 '103.8 51.8 45.1',
 '95.9 40 43.8',
 '88.6 44.8 51.4',
 '83.2 49.5 44.5',
 '86.4 52.4 56.5',
 '108 47 59.7',
 '109.9 54.6 43.2',
 '109.9 54 50.8',
 '91.4 47 50.8',
 '76.8 41.9',
 '94.3 53.3 52.7',
 '94.6 53.3 52.7',
 '97.8 62.2 55.2',
 '94 53.3 45.7',
 '66 43.8 31.1',
 '95.9 52.7 44.5',
 '106.7 46.4 56.5',
 '82.6 45.4 41.3',
 '82.9 45.4 41.3',
 '83.2 45.4 41.3',
 '83.2 45.7 41.3',
 '83.2 45.1 41.3',
 '83.2 45.1 41.6',
 '82.9 45.1 41.3',
 '95.6 54 44.5',
 '88.3 42.5 42.5',
 '149.2',
 '22.5',
 '87 71.1 40',
 '76.2 65.4 42.5',
 '17.3',
 '54',
 '86.4',
 '120.7',
 '119.4',
 '43.5 43.8 29.2',
 '63.5',
 '91.4',
 '113',
 '129.5 87',
 '161.3 75.9',
 '101.6',
 '111.8 83.8',
 '129.5',
 '48.6',
 '37.8',
 '99.1 94',
 '5.4 12.7 14',
 '52.1 41.9 22.9',
 '4.4 42.2 42.2',
 '47 116.2 48.3',
 '71.1 106.7 53.3',
 '72.4 106.4 50.2',
 '66 123.2 55.9',
 '68.6 138.4 48.3',
 '76.2 124.5',
 '67.3 123.2 52.7',
 '62.2 120.7 51.4',
 '73.7 154.9 55.2',
 '74 98.4 48.3',
 '75.6 124.8 54.3',
 '54.6 95.9 37.5',
 '65.4 103.2 51.8',
 '81 102.9',
 '91.4 101.6 54.6',
 '101.6 110.5 55.9',
 '87.6 115.6 49.5',
 '96.5 102.9 54.6',
 '109.2 116.8 53.3',
 '116.2 103.5 55.2',
 '41.3 46.7 27.3',
 '91.4 104.1 50.8',
 '126.4 109.2 43.2',
 '106.7 114.3 47',
 '101.6 102.9 56.2',
 '87.6 102.9 57.2',
 '186.4 100 50.8',
 '77.5 85.7 50.8',
 '103.5 110.8 54.6',
 '101.3 121.9 54',
 '88.3 93.3 54.6',
 '79.7 134.3 60.3',
 '87.6 95.3 52.7',
 '155.6 90.5 53.3',
 '217.8 101 54.6',
 '202.2 109.5 55.6',
 '216.5 109.9 54',
 '200 114.9 58.4',
 '247.7 119.1 61.6',
 '94 76.8 49.5',
 '90.5 67.3 46',
 '49.5 74.9 41.9',
 '83.8 123.8 52.1',
 '73.7 125.7 55.9',
 '83.8 118.7 50.8',
 '93.3 101.6 44.5',
 '70.5 119.4 52.1',
 '84.5 116.8 48.3',
 '83.2 95.3 45.7',
 '94 96.5 51.4',
 '91.4 92.7 53.3',
 '101.6 127.6 58.4',
 '99.7 120.7 55.9',
 '190.5 114 70.5',
 '79.4 41.3 27.9',
 '7.3 8.9',
 '55.6 47.6 27.3',
 '89.2 61 34.6',
 '30.5 72.4 26.7',
 '33 71.8 41.9',
 '31.3 26 17.1',
 '23.8 21',
 '23.7 15.7',
 '23.2 17.1 14.8',
 '85.1 101',
 '6.5',
 '7.5 3',
 '7.6 6 1.4',
 '14.4',
 ...]

In [24]:
#function to split the dimension column into three columns
def split_dimensions(row):
    dimensions = str(row).split(" ")
    if len(dimensions) == 3:
        return [dimension.strip() for dimension in dimensions]
    if len(dimensions) == 2:
        return [dimensions[0].strip(), dimensions[1].strip() , 'null']
    elif len(dimensions) == 1:
        return [dimensions[0].strip(), 'null' ,'null']
    else:
        return ['null', 'null','null']

In [25]:
#Apply Function on our dataframe
df[['hight_col', 'width_col', 'length_col']] = df["New_Dimensions"].apply(lambda x: pd.Series(split_dimensions(x)))

In [26]:
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,New_Dimensions,hight_col,width_col,length_col
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,nan,null,null
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,nan,null,null
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,null,null
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,null,null
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,null,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477799,23.112.2893,False,False,True,860869,NaN,Drawings and Prints,1923,Drawing,Phaeton #24567,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,34.3 × 57.2,34.3,×,57.2
477800,23.112.2894,False,False,True,860870,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton #25538-25539 (#21222),...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33,×,56.5
477801,53.600.1434,False,False,False,860871,NaN,Drawings and Prints,1953,Print,"Forest landscape with cattle drinking, a woman...",...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,29.6 × 19.4,29.6,×,19.4
477802,23.112.2895,False,False,True,860872,NaN,Drawings and Prints,1923,Drawing,Phaeton with folding top,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33,×,56.5
477803,23.112.2896,False,False,True,860873,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,29.8 × 45.1,29.8,×,45.1

In [27]:
df.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL', 'New_Dimensions', 'hight_col', 'width_col',
       'length_col'],
      dtype='object')

In [28]:
df['hight_col'].unique().tolist()

['nan',
 '1.7',
 '1.3',
 '2.9',
 '1.9',
 '5.4',
 '7',
 '61.9',
 '49.4',
 '101.6',
 '30.5',
 '31.4',
 '27.9',
 '16.7',
 '15.9',
 '78.4',
 '68.6',
 '40.6',
 '43.2',
 '29.2',
 '41.9',
 '58.4',
 '57.2',
 '64.1',
 '59.7',
 '47',
 '53.3',
 '78.1',
 '54',
 '45.1',
 '64.8',
 '41',
 '48.9',
 '52.7',
 '47.6',
 '59.1',
 '28.9',
 '61',
 'null',
 '53.7',
 '80',
 '63.5',
 '57.5',
 '9.2',
 '109.2',
 '210.8',
 '640.1',
 '44.5',
 '45.4',
 '86.4',
 '111.8',
 '113',
 '121.9',
 '14',
 '106.7',
 '119.4',
 '116.8',
 '97.2',
 '127.6',
 '115.6',
 '117.5',
 '99.1',
 '99.7',
 '123.8',
 '82.6',
 '108',
 '104.1',
 '81.9',
 '106.4',
 '128.3',
 '94.9',
 '98.4',
 '99.4',
 '107',
 '100.3',
 '13.3',
 '71.1',
 '91.4',
 '89.2',
 '113.7',
 '114.9',
 '106',
 '103.2',
 '97.8',
 '28.6',
 '90.2',
 '103.5',
 '163.8',
 '92.1',
 '109.9',
 '87.9',
 '110.5',
 '114.3',
 '150.5',
 '102.9',
 '116.2',
 '134.6',
 '89.5',
 '83.5',
 '84.5',
 '131.4',
 '94',
 '83.8',
 '90.5',
 '89.9',
 '96.5',
 '92.7',
 '95.9',
 '93.3',
 '127',
 '125.7',
 '85.7',
 '83.2',
 '117.8',
 '54.6',
 '66.7',
 '335.3',
 '74.9',
 '11.1',
 '16.5',
 '6.4',
 '5.1',
 '4.4',
 '4.1',
 '3.3',
 '12.4',
 '7.3',
 '9.5',
 '20.3',
 '19.1',
 '27.6',
 '80.6',
 '87.6',
 '24',
 '23.5',
 '23.2',
 '26',
 '42.5',
 '5.7',
 '24.8',
 '6',
 '14.6',
 '10.5',
 '52.1',
 '15.2',
 '10.8',
 '34.3',
 '6.7',
 '12.1',
 '34.9',
 '33',
 '105.4',
 '66',
 '11.3',
 '14.9',
 '31.1',
 '26.7',
 '28.4',
 '11.4',
 '182.9',
 '188',
 '16.8',
 '8.6',
 '29.8',
 '18.4',
 '6.2',
 '8.7',
 '17.8',
 '18.3',
 '13',
 '7.9',
 '8.1',
 '8.9',
 '7.6',
 '15.1',
 '13.7',
 '9',
 '7.5',
 '8.4',
 '12.6',
 '9.8',
 '7.8',
 '18.1',
 '10.3',
 '10.2',
 '24.1',
 '22.2',
 '196.9',
 '223.8',
 '251.8',
 '245.1',
 '81.3',
 '205.7',
 '180.3',
 '299.7',
 '271.1',
 '161',
 '130.8',
 '35.6',
 '50.8',
 '44',
 '50.2',
 '67.3',
 '42.2',
 '60.3',
 '37.5',
 '8.3',
 '25.4',
 '12.7',
 '4.8',
 '14.3',
 '34',
 '15.6',
 '16.2',
 '43.5',
 '34.6',
 '31.8',
 '35.2',
 '32.9',
 '33.7',
 '32.1',
 '21.9',
 '21.6',
 '126.4',
 '4.9',
 '46.4',
 '48.4',
 '10',
 '19.4',
 '27.3',
 '231.8',
 '242.6',
 '5.6',
 '5.5',
 '15.7',
 '15.4',
 '30.8',
 '21.3',
 '18.7',
 '17.1',
 '25.1',
 '20.6',
 '11',
 '22.9',
 '11.7',
 '2.5',
 '3.5',
 '40.3',
 '2.7',
 '10.4',
 '20',
 '21',
 '20.5',
 '25.2',
 '30.3',
 '26.8',
 '23.7',
 '30.6',
 '23.0',
 '23.8',
 '22.4',
 '26.5',
 '23.3',
 '13.2',
 '12.5',
 '20.2',
 '14.1',
 '16',
 '3.8',
 '12.9',
 '5.9',
 '4.3',
 '3.2',
 '2.2',
 '1.6',
 '1',
 '36.8',
 '48.3',
 '65.4',
 '85.1',
 '0.8',
 '22.5',
 '76.2',
 '87.3',
 '11.6',
 '11.9',
 '2.4',
 '45.7',
 '199.4',
 '112.4',
 '108.9',
 '243.8',
 '135.6',
 '210.2',
 '12.2',
 '19.7',
 '55.9',
 '3',
 '70.8',
 '73.7',
 '37.8',
 '70.5',
 '55.2',
 '62.9',
 '62.2',
 '78.6',
 '17.5',
 '58.1',
 '50.5',
 '49.5',
 'a',
 '72.4',
 '165.1',
 '172.7',
 '74.3',
 '157.5',
 '41.3',
 '108.6',
 '155.9',
 '39.4',
 '24.9',
 '26.4',
 '17.6',
 '22.7',
 '17.9',
 '29.1',
 '5.2',
 '24.4',
 '42.9',
 '27.8',
 '34.1',
 '25.9',
 '28.1',
 '28.3',
 '28.36',
 '29.4',
 '33.3',
 '17',
 '142.2',
 '88.3',
 '73',
 '71.8',
 '72.7',
 '73.3',
 '69.2',
 '78.7',
 '76.8',
 '9.7',
 '17.3',
 '13.8',
 '3.7',
 '18.9',
 '19.5',
 '18.6',
 '45.6',
 '32.4',
 '65.7',
 '79.4',
 '75.7',
 '133.4',
 '104.5',
 '95.3',
 '101',
 '88.9',
 '104.8',
 '107.3',
 '116.5',
 '96.8',
 '134',
 '96.2',
 '101.3',
 '98.1',
 '58.7',
 '93',
 '94.6',
 '98.7',
 '86.7',
 '105.1',
 '82.1',
 '51.4',
 '100.6',
 '86',
 '82.2',
 '81.6',
 '71.4',
 '94.3',
 '79.1',
 '141.6',
 '101.9',
 '87',
 '120.7',
 '96.4',
 '84.8',
 '114',
 '94.5',
 '90.8',
 '103.8',
 '88.6',
 '82.9',
 '95.6',
 '149.2',
 '129.5',
 '161.3',
 '48.6',
 '74',
 '75.6',
 '81',
 '186.4',
 '77.5',
 '79.7',
 '155.6',
 '217.8',
 '202.2',
 '216.5',
 '200',
 '247.7',
 '190.5',
 '55.6',
 '31.3',
 '6.5',
 '14.4',
 '4.6',
 '46.5',
 '46',
 '232.1',
 '39.1',
 '33.5',
 '36.7',
 '40',
 '26.2',
 '25.6',
 '33.2',
 '339.1',
 '426.7',
 '13.5',
 '24.6',
 '138.4',
 '236.2',
 '221.6',
 '130.2',
 '203.2',
 '177.8',
 '170.2',
 '206.7',
 '38.7',
 '35.9',
 '10.6',
 '9.4',
 '38.1',
 '37.1',
 '16.4',
 '22.1',
 '21.4',
 '30',
 '14.8',
 '42.7',
 '41.1',
 '30.2',
 '7.1',
 '29.5',
 '27',
 '4..1',
 '147.3',
 '123.2',
 '137.8',
 '152.4',
 '143.5',
 '146.7',
 '186.1',
 '91.8',
 '73.8',
 '220',
 '241.3',
 '245.4',
 '237.5',
 '174.6',
 '206.1',
 '202.6',
 '227.3',
 '213.4',
 '270.5',
 '231.1',
 '240.5',
 '266.7',
 '233',
 '259.1',
 '242.3',
 '228.6',
 '61.3',
 '69.9',
 '75.1',
 '36.5',
 '2.1',
 '205.1',
 '59.4',
 '304.8',
 '337.2',
 '602',
 '212.7',
 '57.8',
 '77.8',
 '75.2',
 '162.6',
 '151.1',
 '65.1',
 '72.9',
 '25.7',
 '221',
 '123.5',
 '112.1',
 '125.1',
 '120',
 '121.3',
 '110.8',
 '139.7',
 '54.3',
 '62.4',
 '275',
 '174.9',
 '218.4',
 '398.8',
 '141',
 '156.2',
 '56.5',
 '36.2',
 '85.4',
 '154.3',
 '159.7',
 '4',
 '41.8',
 '160',
 '63.2',
 '56.2',
 '36.4',
 '41.6',
 '47.3',
 '135.9',
 '365.8',
 '182.2',
 '162.9',
 '52.4',
 '67.9',
 '137.2',
 '175.9',
 '6.8',
 '19.2',
 '590.6',
 '62.5',
 '72.1',
 '178.4',
 '225.4',
 '132.1',
 '251.5',
 '219.7',
 '158.8',
 '220.3',
 '177.2',
 '213.7',
 '38.4',
 '23',
 '21.1',
 '37.6',
 '149.9',
 '43.7',
 '27.1',
 '37.9',
 '65.2',
 '37.3',
 '36',
 '34.8',
 '40.2',
 '56.8',
 '32.7',
 '223.5',
 '184.2',
 '21.7',
 '146.1',
 '61.8',
 '122.6',
 '144.8',
 '156.8',
 '128.9',
 '165.6',
 '20.8',
 '54.9',
 '154.9',
 '139.1',
 '75.4',
 '44.8',
 '158.4',
 '52.9',
 '169.5',
 '51.8',
 '124.5',
 '235',
 '248.9',
 '642.6',
 'h',
 '252.1',
 '0.6',
 '107.6',
 '291.5',
 '284.5',
 '198.1',
 '281.9',
 '91.1',
 '42.1',
 '31.9',
 '14.',
 '21.0',
 '1.4',
 '69.5',
 '27.5',
 '35.1',
 '47.5',
 '54.5',
 '59.5',
 '115.3',
 '32.5',
 'in',
 '80.3',
 '68.3',
 '4.7',
 '61.6',
 '39.8',
 '111.1',
 '92.4',
 '214.6',
 '166.4',
 '207',
 '37',
 '1.1',
 '109.5',
 '135.3',
 '110.2',
 '20.0',
 '581.7',
 '24.3',
 '66.8',
 '63.8',
 '66.4',
 '235.6',
 '214.3',
 '265.4',
 '264.2',
 '232.4',
 '215.9',
 '238.1',
 '209.6',
 '268',
 '252.7',
 '249.6',
 '215.3',
 '241.9',
 '253.4',
 '273.1',
 '140.7',
 '68.9',
 '74.6',
 '39.7',
 '56.7',
 '49.1',
 '468.3',
 '35.4',
 '34.4',
 '21.5',
 '51',
 '43',
 '42.4',
 '262.9',
 '308.6',
 '330.2',
 '312.4',
 '327.7',
 '307.3',
 '194.3',
 '195.6',
 '193.7',
 '128',
 '58.9',
 '49.2',
 '43.8',
 '396.2',
 '191.1',
 '69.7',
 '153',
 '219.1',
 '342.9',
 '125.9',
 '53',
 '74.1',
 '76.4',
 '82.23',
 '31',
 '29.21',
 '13.34',
 '14.61',
 '24.77',
 '13.97',
 '47.63',
 '132.7',
 '46.7',
 '256.5',
 '176.2',
 '183',
 '75.5',
 '3.9',
 '44.9',
 '81.8',
 '186.7',
 '148.6',
 '126.7',
 '142.9',
 '63.7',
 '54.1',
 '15.8',
 '144.1',
 '31.7',
 '29.7',
 '38.6',
 '38.9',
 '31.6',
 '54.8',
 '49.8',
 '45.9',
 '32.2',
 '65.6',
 '67.6',
 '60',
 '140',
 '175.8',
 '177.5',
 '188.3',
 '188.6',
 '168',
 '151.8',
 '76.7',
 '122.2',
 '60.6',
 '47.9',
 '76.5',
 '51.1',
 '84.1',
 '77',
 '239.7',
 '61.1',
 '99.9',
 '234.3',
 '153.4',
 '208.3',
 '127.3',
 '167.6',
 '119.7',
 '102.2',
 '75.9',
 '306.1',
 '77.2',
 '27.54',
 '9.3',
 '63.6',
 '67',
 '61.2',
 '99.8',
 '86.6',
 '91.7',
 '115.1',
 '40.8',
 '112.7',
 '196.5',
 '41.4',
 '141.9',
 '172.4',
 '197.2',
 '76',
 '86.5',
 '48.1',
 '46.8',
 '70.2',
 '153.7',
 '93.9',
 '117.2',
 '58.6',
 '161.9',
 '378.5',
 '129.2',
 '13.16',
 '100',
 '97.5',
 '5.3',
 '40.1',
 '137.6',
 '50.6',
 '28.7',
 '37.2',
 '129.7',
 '187.3',
 '64',
 '292.1',
 '91.6',
 '5',
 '4.5',
 '72.3',
 '7.2',
 '91.76',
 '140.3',
 '60.8',
 '97.3',
 '148',
 '7.7',
 '3.1',
 '62.6',
 '114.6',
 '262.3',
 '258.4',
 '53.2',
 '33.8',
 '60.5',
 '208.6',
 '214',
 '32.8',
 '53.8',
 '47.8',
 '19.05',
 '16.51',
 '17.15',
 '30.48',
 '15.24',
 '181.9',
 '55.3',
 '19.8',
 '45.2',
 '208.9',
 '128.6',
 '6.1',
 '138.1',
 '100.7',
 '185.7',
 '7.4',
 'sight',
 '1.27',
 '43.6',
 '11.8',
 '91',
 '49.9',
 '125.2',
 '66.5',
 '51.3',
 '43.3',
 '53.6',
 '63',
 '91.9',
 '34.92',
 '93.7',
 '3.6',
 '64.3',
 '75.3',
 '11.2',
 'Object',
 '100.5',
 '86.2',
 '44.3',
 '55.7',
 '193',
 '178.8',
 '193.4',
 '107.5',
 '6.3',
 '134.7',
 '6.6',
 '38',
 '154',
 '279.4',
 '124.1',
 '61.4',
 '246.4',
 '189.9',
 '200.7',
 '236.9',
 '226.1',
 '211.5',
 '477.5',
 '287',
 '171.5',
 '612.1',
 '387',
 '197.5',
 '203.8',
 '254',
 '222.9',
 '230.5',
 '212.1',
 '220.7',
 '276.9',
 '309.9',
 '261',
 '264.8',
 '255.3',
 '277.5',
 '257.8',
 '212.4',
 '274.3',
 '250.2',
 '263.5',
 '244.5',
 '249.9',
 '166.7',
 '155.3',
 '179.1',
 '185.4',
 '345.4',
 '406.4',
 '136.5',
 '118.1',
 '261.6',
 '464.8',
 '1242.1',
 '322.6',
 '201.9',
 '61.5',
 '289.6',
 '179.7',
 '44.6',
 '151.4',
 '447',
 '609.6',
 '599.4',
 '294',
 '260.4',
 '233.7',
 '207.6',
 '275.6',
 '240',
 '280',
 '238.8',
 '269.2',
 '269.9',
 '211.8',
 '273.4',
 '285.8',
 '224.2',
 '259.7',
 '192.4',
 '222.3',
 '174',
 '189.2',
 '173.4',
 '313.1',
 '316.2',
 '297.2',
 '375.9',
 '487.7',
 '350.5',
 '411.5',
 '315',
 '774.7',
 '377.2',
 '462.3',
 '904.2',
 '548.6',
 '87.7',
 '29.9',
 '44.1',
 '191.8',
 '1019.8',
 '558.8',
 '792.5',
 '1005.8',
 '731.5',
 '853.4',
 '532.1',
 '421.6',
 '5.8',
 '12.8',
 '94.8',
 '504',
 '11.43',
 '11.11',
 '118.7',
 '240.7',
 '53.5',
 '87.5',
 '8.5',
 '9.1',
 '10.1',
 '2.3',
 '8',
 '8.2',
 '4.2',
 '11.5',
 '6.9',
 '3.4',
 '10.7',
 '40.5',
 '272.4',
 '38.3',
 '54.0',
 '283.8',
 '71.9',
 '35.5',
 '29',
 ...]

In [29]:
df['width_col'].unique().tolist()

['null',
 '8.9',
 '37.1',
 '33',
 '64.8',
 '22.9',
 '63.5',
 '58.4',
 '54.6',
 '56.5',
 '53.3',
 '71.1',
 '45.1',
 '61',
 '38.7',
 '49.5',
 '43.2',
 '59.7',
 '40',
 '46.4',
 '36.8',
 '44.5',
 '68.6',
 '29.2',
 '25.4',
 '35.6',
 '38.1',
 '27.3',
 '148.6',
 '701',
 '74.9',
 '21.6',
 '66',
 '55.9',
 '57.8',
 '63.2',
 '62.9',
 '62.2',
 '54.3',
 '84.5',
 '82.6',
 '80',
 '47',
 '67.9',
 '53',
 '12.1',
 '57.2',
 '61.9',
 '54.9',
 '25.2',
 '52.1',
 '76.2',
 '61.6',
 '64.5',
 '71.8',
 '51.8',
 '70.2',
 '52.7',
 '83.8',
 '73.7',
 '56.2',
 '69.9',
 '64.1',
 '65.1',
 '72.4',
 '57.5',
 '67.3',
 '53.7',
 '59.1',
 '54',
 '45.7',
 '94',
 '24.8',
 '259.1',
 '16.5',
 '10.8',
 '614.7',
 '25.1',
 '80.6',
 '27.6',
 '28.9',
 '2.2',
 '1.9',
 '15.2',
 '11.7',
 '26.7',
 '20.3',
 '16.8',
 '14.6',
 '32.7',
 '48.3',
 '13.3',
 '34.3',
 '36.7',
 '15.9',
 '78.7',
 '134',
 '155.6',
 '167.6',
 '142.9',
 '120.7',
 '134.3',
 '176.5',
 '148.9',
 '99.1',
 '125.1',
 '×',
 '18.6',
 '85.1',
 '180.3',
 '77.5',
 '238.8',
 '90.2',
 '60.6',
 '140.7',
 '6.7',
 '5.1',
 '7.3',
 '6',
 '14.3',
 '10.2',
 '10.5',
 '23.5',
 '7.6',
 '9.8',
 '6.4',
 '11.4',
 '28.6',
 '26',
 '24.1',
 '8.7',
 '8.3',
 '42.9',
 '37.5',
 '41.9',
 '39.7',
 '41.3',
 '40.5',
 '39.4',
 '34.9',
 '38.4',
 '116.8',
 '113',
 '14.8',
 '30.8',
 '1.7',
 '124.5',
 '152.4',
 '17.8',
 '15.6',
 '15.7',
 '5.6',
 '5.4',
 '5.2',
 '7',
 '2.9',
 '14.9',
 '',
 '21.7',
 '20.6',
 '25.7',
 '18.1',
 '35.1',
 '30.3',
 '32.5',
 '13.7',
 '24.4',
 '11',
 '9.4',
 '24.9',
 '7.8',
 '8.1',
 '66.7',
 '13.1',
 '12.7',
 '21.9',
 '74.3',
 '58.1',
 '14',
 '4.8',
 '17.5',
 '13',
 '8.6',
 '9.2',
 '9.5',
 '41',
 '3',
 '19.1',
 '3.8',
 '7.9',
 '67.6',
 '8.4',
 '13.2',
 '31.1',
 '47.6',
 '43.8',
 '43.5',
 '48.7',
 '4.4',
 '6.2',
 '3.2',
 '98.7',
 '89.2',
 '92.7',
 '5.7',
 '2.5',
 '134.6',
 '168.3',
 '81.3',
 '183.4',
 '106.7',
 '186.4',
 '154.9',
 '29.4',
 '19.4',
 '12.4',
 '51.3',
 '30.5',
 '42.5',
 '50.2',
 '33.7',
 '27',
 '15.4',
 '16.4',
 '12.2',
 '10',
 '12.9',
 '16.2',
 '20',
 '82.2',
 '90.8',
 '144.8',
 '88.9',
 '86.4',
 '87.6',
 '91.4',
 '92.4',
 '90.5',
 '89.5',
 '90.6',
 '86',
 '51.4',
 '4.9',
 '6.8',
 '5.9',
 '45.4',
 '84.8',
 '119.4',
 '31.8',
 '48.9',
 '50.8',
 '55.2',
 '51.1',
 '49.8',
 '56.8',
 '60.3',
 '55.6',
 '36.2',
 '40.3',
 '52.4',
 '50.5',
 '39.1',
 '70.8',
 '47.1',
 '46.7',
 '44',
 '44.8',
 '48.6',
 '60',
 '47.3',
 '44.1',
 '65.4',
 '87',
 '75.9',
 '42.2',
 '116.2',
 '106.4',
 '123.2',
 '138.4',
 '98.4',
 '124.8',
 '95.9',
 '103.2',
 '102.9',
 '101.6',
 '110.5',
 '115.6',
 '103.5',
 '104.1',
 '109.2',
 '114.3',
 '100',
 '85.7',
 '110.8',
 '121.9',
 '93.3',
 '95.3',
 '101',
 '109.5',
 '109.9',
 '114.9',
 '119.1',
 '76.8',
 '123.8',
 '125.7',
 '118.7',
 '96.5',
 '127.6',
 '114',
 '21',
 '17.1',
 '1.3',
 '3.5',
 '35.9',
 '34.6',
 '113.3',
 '23.2',
 '26.4',
 '22.1',
 '27.8',
 '454.7',
 '4.1',
 '71.6',
 '27.5',
 '26.5',
 '31.3',
 '40.6',
 '92.1',
 '127',
 '93',
 '100.3',
 '172.1',
 '185.4',
 '16.7',
 '9',
 '25.6',
 '10.6',
 '11.1',
 '30.2',
 '22.7',
 '11.9',
 '18.7',
 '22.4',
 '22.2',
 '28.7',
 '22.5',
 '19.2',
 '16',
 '24',
 '18.9',
 '11.6',
 '33.5',
 '32.4',
 '23.8',
 '24.6',
 '27.9',
 '18.4',
 '13.8',
 '14.1',
 '11.3',
 '14.4',
 '20.5',
 '10.3',
 '126.4',
 '94.6',
 '111.8',
 '112.4',
 '7.1',
 '2.7',
 '20.8',
 '100.6',
 '120',
 '62.5',
 '112.1',
 '115.9',
 '111.4',
 '217.2',
 '182.9',
 '172.7',
 '133',
 '141.6',
 '122.2',
 '135.3',
 '121.6',
 '179.1',
 '174',
 '79.4',
 '310.5',
 '129.5',
 '415.9',
 '136.5',
 '23',
 '17.3',
 '37.8',
 '17.6',
 '175.3',
 '133.4',
 '132.1',
 '33.3',
 '42.1',
 '607.1',
 '191.8',
 '91.1',
 '86.7',
 '73',
 '163.8',
 '151.8',
 '108',
 '96.2',
 '19.7',
 '83.2',
 '72.7',
 '213.4',
 '105.4',
 '38.6',
 '6.5',
 '7.5',
 '144.1',
 '75.2',
 '201.9',
 '279.4',
 '113.7',
 '117.5',
 '171.5',
 '139.7',
 '85.4',
 '97.2',
 '114.6',
 '35.2',
 '28.3',
 '26.2',
 '190.5',
 '195.6',
 '52.5',
 '29.8',
 '31.4',
 '37.6',
 '89.9',
 '141',
 '189.2',
 '146.1',
 '108.6',
 '118.1',
 '1.6',
 '1.4',
 '28.1',
 '29.5',
 '348.6',
 '99.7',
 '101.3',
 '102.2',
 '110.1',
 '21.3',
 '15.1',
 '12.8',
 '25.9',
 '27.1',
 '47.9',
 '19.5',
 '153',
 '146.7',
 '170.2',
 '23.7',
 '31.9',
 '9.7',
 '210.8',
 '131.4',
 '147.3',
 '292.1',
 '67',
 '78.1',
 '60.5',
 '105.7',
 '165.6',
 '160',
 '137.2',
 '248.3',
 '240.3',
 '188',
 '2.4',
 '39.5',
 '81',
 '3.3',
 '4.6',
 '13.5',
 '12.5',
 '3.7',
 '69.2',
 '189.9',
 '149.9',
 '508',
 '500.4',
 '499.1',
 '4.3',
 '2.1',
 '23.3',
 '177.2',
 '135.9',
 '130.8',
 '122.6',
 '111.1',
 '118',
 '107.3',
 '303.5',
 '34',
 '37.3',
 '46',
 '49.2',
 '35.7',
 '33.2',
 '40.2',
 '43',
 '36',
 '19.8',
 '17',
 '18.3',
 '20.2',
 '21.1',
 '41.8',
 '94.9',
 '72.1',
 'nine',
 '17.9',
 '44.3',
 '40.8',
 '41.4',
 '30',
 '157.5',
 '142.2',
 '192.4',
 '212.1',
 '161.3',
 '200',
 '226.1',
 '194',
 '151.1',
 '1.1',
 '1',
 '203.2',
 '224.2',
 '151.4',
 '250.2',
 '197.6',
 '248.9',
 '228',
 '227.3',
 '193',
 '209.6',
 '203.8',
 '215.3',
 '38.9',
 '198.1',
 '194.9',
 '158.8',
 '186.1',
 '201.6',
 '233.7',
 '170.8',
 '165.1',
 '51.9',
 '88.3',
 '21.4',
 '154',
 '58.7',
 '395',
 '66.4',
 '68.9',
 '24.3',
 '80.3',
 '29.1',
 '32.1',
 '32.2',
 '32.9',
 '33.8',
 '104.8',
 '7.7',
 '93.8',
 '372.1',
 '236.2',
 '393.4',
 '289.6',
 '299.7',
 '240',
 '596.9',
 '76.5',
 '243.8',
 '204',
 '75.6',
 '106',
 '142.6',
 '130.2',
 '541',
 '174.9',
 '74',
 '71.4',
 '20.96',
 '323.2',
 '161.6',
 '101.9',
 '84.1',
 '37',
 '110.2',
 '96.8',
 '51',
 '306.7',
 '39.8',
 '108.3',
 '2.6',
 '.',
 '102.6',
 '78.9',
 '91.8',
 '77.8',
 '46.5',
 '262.9',
 '131.6',
 '50.6',
 '36.5',
 '94.8',
 '37.9',
 '31',
 '41.6',
 '46.2',
 '45.6',
 '91.12',
 '106.5',
 '63',
 '66.2',
 '65.7',
 '28.4',
 '97',
 '61.1',
 '35.4',
 '59.4',
 '92.6',
 '61.3',
 '41.1',
 '128.3',
 '152.1',
 '23.6',
 '103.8',
 '92.2',
 '49.9',
 '114.5',
 '46.3',
 '302.9',
 '184.5',
 '101.8',
 '152.7',
 '184.2',
 '183.5',
 '119.7',
 '49.4',
 '47.5',
 '81.9',
 '122.9',
 '6.9',
 '91.6',
 '121.3',
 '233',
 '31.6',
 '26.8',
 '50.3',
 '38.3',
 '5.26',
 '68.8',
 '215.9',
 '57.1',
 '42.6',
 '57.3',
 '76.4',
 '121',
 '217.8',
 '76.7',
 '159.7',
 '95.6',
 '54.5',
 '45.2',
 '255.3',
 '145.4',
 '3.4',
 '53.5',
 '181',
 '54.8',
 '128',
 '66.3',
 '193.7',
 '127.8',
 '187.3',
 '56',
 '60.2',
 '56.7',
 '65.6',
 '71.5',
 '137.8',
 '5.5',
 '53.2',
 '107.2',
 '77.2',
 '160.3',
 '31.2',
 '285.4',
 '301',
 '68.7',
 '70.3',
 '198.8',
 '73.6',
 '168.6',
 '104.5',
 '3.1',
 '98.1',
 '122',
 '647.7',
 '25',
 '7.16',
 '81.1',
 '114.7',
 '55.1',
 '4',
 '5.86',
 '97.8',
 '153.7',
 '111.6',
 '119.9',
 '100.7',
 '73.3',
 '36.4',
 '61.4',
 '63.8',
 '146.4',
 '64.3',
 '61.5',
 '214.6',
 '126.7',
 '71.9',
 '3.9',
 '69.4',
 '156.8',
 '4.7',
 '73.98',
 '69.5',
 '99',
 '63.6',
 '70.5',
 '87.3',
 '127.3',
 '99.8',
 '129.9',
 '34.4',
 '79.2',
 '58.6',
 '74.6',
 '5.3',
 '148',
 '4.5',
 '62.7',
 '36.3',
 '43.3',
 '34.8',
 '29.7',
 '50',
 '52.9',
 '105.1',
 '213.7',
 '13.97',
 '19.69',
 '69.7',
 '23.1',
 '115.3',
 '152.6',
 '53.8',
 '161',
 '10.1',
 '89.3',
 '271.8',
 '76.3',
 '200.3',
 '63.7',
 '72',
 '132.7',
 '47.8',
 '63.9',
 '75',
 '5',
 '42.7',
 '49',
 '28',
 '89.4',
 '147.8',
 '26.67',
 '21.8',
 '149.2',
 '130.5',
 'diameter',
 '96.6',
 '43.7',
 '180.7',
 '68.3',
 '204.5',
 '134.9',
 '103.3',
 '91.7',
 '55.7',
 '91',
 '17.2',
 '32',
 '46.8',
 '6.1',
 '12',
 '57.9',
 '173.4',
 '182.2',
 '166.4',
 '252.4',
 '220.3',
 '569',
 '373.4',
 '365.8',
 '411.5',
 '205.7',
 '165.7',
 '261.6',
 '179.4',
 '229.9',
 '214',
 '242.9',
 '223.5',
 '264.8',
 '335.3',
 '288.9',
 '235.6',
 '221.6',
 '246.4',
 '216.5',
 '261',
 '228.6',
 '208.9',
 '231.1',
 '207',
 '202.6',
 '264.2',
 '188.6',
 '181.6',
 '269.2',
 '198.6',
 '1219.2',
 '254',
 '273.1',
 '222.9',
 '252.7',
 '196.9',
 '272.4',
 '235',
 '214.2',
 '271.1',
 '225.4',
 '263.5',
 '194.3',
 '249.6',
 '291.1',
 '186.7',
 '221.3',
 '226.7',
 '198.4',
 '201.3',
 '205.1',
 '309.9',
 '224.8',
 '177.8',
 '216.9',
 '210.2',
 '192.7',
 '200.7',
 '266.7',
 '276.2',
 '221',
 '723.9',
 '337.8',
 '218.4',
 '396.2',
 '284.5',
 '29.9',
 '251.5',
 '136.8',
 '2',
 '8',
 '6.6',
 '10.4',
 '6.3',
 '5.8',
 'in.',
 '49.7',
 '171.1',
 '107.4',
 '30.6',
 '52.8',
 '192.1',
 '62.4',
 '8.5',
 'x.',
 '4.2',
 '8.2',
 '2.3',
 '8.8',
 '1.8',
 '2.8',
 '7.4',
 '208.3',
 '163.2',
 '89.1',
 '767.1',
 '27.7',
 '100.5',
 '51.5',
 '81.8',
 '64.6',
 '50.4',
 '175.9',
 '173.2',
 '242.6',
 '79.1',
 '91.9',
 '22.6',
 '47.2',
 '61.0',
 '19.3',
 '39',
 '158.1',
 '68',
 '94.5',
 '79.5',
 '74.8',
 '32.6',
 '38.2',
 'size',
 '55.5',
 '43.4',
 '55.8',
 '17.7',
 '24.5',
 '34.1',
 '34.7',
 '45.8',
 '54.7',
 '71',
 '44.6',
 '57.6',
 '35.5',
 '20.1',
 '22',
 '35.8',
 '139.1',
 '138.1',
 '66.5',
 '15.24',
 '162.6',
 '835.7',
 '163.5',
 '629.9',
 '48.1',
 '54.1',
 '39.2',
 '67.8',
 '197.2',
 'stereographs',
 '16.6',
 ',',
 '121.4',
 '219.7',
 '120.3',
 '1005.8',
 '381',
 '117.8',
 '43.18',
 '17.77',
 'com',
 'kg',
 'scabbard',
 '8.26',
 'side',
 'g',
 '5.08',
 'X',
 '33.6',
 'm',
 'b',
 'plate',
 'helmet',
 '72.6',
 'b,',
 'chausses',
 'width',
 'tang',
 'blade',
 'to',
 'mm',
 '9.6',
 '20.9',
 '6.0',
 '26.35',
 ...]

In [30]:
df['length_col'].unique().tolist()

['null',
 '7',
 '13',
 '23.5',
 '87.6',
 '35.2',
 '34.3',
 '20.6',
 '29.8',
 '30.5',
 '27.3',
 '33',
 '40.6',
 '37.8',
 '59.7',
 '88.9',
 '52.1',
 '20',
 '48.3',
 '44.5',
 '38.1',
 '57.2',
 '42.9',
 '38.4',
 '61',
 '53.3',
 '43.2',
 '55.9',
 '44.8',
 '47',
 '58.4',
 '57.9',
 '54.6',
 '54',
 '40',
 '45.7',
 '49.5',
 '71.1',
 '48.9',
 '36.2',
 '45.1',
 '42.2',
 '56.5',
 '76.2',
 '64.8',
 '46.4',
 '67.9',
 '52.7',
 '68.6',
 '83.8',
 '67',
 '50.8',
 '62.9',
 '69.9',
 '63.5',
 '73.7',
 '66.4',
 '66.7',
 '60.3',
 '74.6',
 '78.7',
 '43.5',
 '44.1',
 '54.3',
 '64.3',
 '38.7',
 '65.4',
 '7.9',
 '2.5',
 '5.4',
 '2.9',
 '11.7',
 '9.2',
 '20.3',
 '16.8',
 '14.6',
 '32.7',
 '18.6',
 '24.8',
 '28.9',
 '193',
 '195.6',
 '214.6',
 '196.2',
 '179.1',
 '227.3',
 '201.9',
 '205.7',
 '42.5',
 '10.2',
 '35.6',
 '24.1',
 '42.4',
 '5.1',
 '8.7',
 '31.1',
 '62.2',
 '7.6',
 '69.5',
 '1',
 '1.1',
 '0.8',
 '34.9',
 'Diam.',
 '11',
 '13.7',
 '9.4',
 '21.9',
 '20.2',
 '6',
 '8.9',
 '8.1',
 '7.8',
 '6.7',
 '8.3',
 '45.4',
 '43.8',
 '6.4',
 '10.8',
 '7.3',
 '33.7',
 '13.3',
 '8.6',
 '12.1',
 '5.7',
 '22.9',
 '4.3',
 '21.6',
 '12.7',
 '39.4',
 '27.6',
 '18.7',
 '28.7',
 '57.5',
 '56.8',
 '11.4',
 '25.4',
 '46.7',
 '10.3',
 '15.9',
 '29.5',
 '36.8',
 '32.1',
 '16.4',
 '26.4',
 '16.5',
 '8.4',
 '27.9',
 '86.4',
 '90.8',
 '85.4',
 '96.5',
 '41.9',
 '44.9',
 '91.1',
 '84.8',
 '18.1',
 '37.5',
 '41',
 '41.3',
 '50.2',
 '51.4',
 '49.2',
 '55.2',
 '51.1',
 '57.8',
 '66',
 '46.2',
 '47.9',
 '47.6',
 '53.7',
 '49.8',
 '41.6',
 '29.2',
 '14',
 '51.8',
 '56.2',
 '55.6',
 '61.6',
 '46',
 '70.5',
 '34.6',
 '26.7',
 '17.1',
 '14.8',
 '1.4',
 '6.5',
 '19.7',
 '3.8',
 '4.8',
 '22.4',
 '15.7',
 '11.1',
 '14.9',
 '14.3',
 '44',
 '22.2',
 '22.7',
 '16.2',
 '189.2',
 '59.1',
 '178.4',
 '17.5',
 '12.2',
 '21',
 '13.5',
 '13.8',
 '37',
 '33.3',
 '15.6',
 '15.2',
 '27.5',
 '24.4',
 '23.7',
 '12.4',
 '12.5',
 '10.6',
 '11.9',
 '19.4',
 '35.4',
 '26.5',
 '94.3',
 '116.8',
 '114.3',
 '9.5',
 '6.8',
 '9',
 '10',
 '17.8',
 '23.8',
 '21.7',
 '2.7',
 '5.2',
 '28.6',
 '62.5',
 '64.1',
 '48.6',
 '71.4',
 '122.9',
 '99.7',
 '157.5',
 '90.2',
 '121.3',
 '121.9',
 '245.1',
 '84.5',
 '127',
 '153',
 '136.5',
 '16.7',
 '19.1',
 '244.2',
 '0.2',
 '52.4',
 '54.9',
 '50.5',
 '73',
 '150.5',
 '116.2',
 '93.3',
 '64.5',
 '72.1',
 '94',
 '71.8',
 '81.3',
 '65.7',
 '1.3',
 '80.6',
 '31.8',
 '85.1',
 '49.7',
 '42.7',
 '26',
 '22.5',
 '156.8',
 '91.4',
 '113.7',
 '180.3',
 '109.2',
 '122.6',
 '108.6',
 '128.3',
 '82.6',
 '88.3',
 '20.8',
 '115.6',
 '3.2',
 '4.9',
 '36.5',
 '17.9',
 '10.5',
 '4.1',
 '86',
 '67.3',
 '74.9',
 '4.4',
 '2.2',
 '3.3',
 '1.6',
 '332.7',
 '1.9',
 '153.7',
 '75.6',
 '77.5',
 '89.5',
 '84.1',
 '7.1',
 '108',
 '106.7',
 '5.6',
 '12.9',
 '4',
 '9.8',
 '15.4',
 '18.4',
 '2.1',
 '33.2',
 '30.2',
 '28.3',
 '25.2',
 '21.3',
 '45.6',
 '111.9',
 '4.6',
 'parts',
 '5.9',
 '47.3',
 '2.4',
 '7.5',
 '6.2',
 '32.4',
 '66.5',
 '76.5',
 '182.9',
 '25.6',
 '307.3',
 '396.2',
 '81.9',
 '92.7',
 '79.1',
 '105.4',
 '89.9',
 '78.1',
 '58.1',
 '111.8',
 '101.6',
 '25.7',
 '27',
 '40.3',
 '25.1',
 '9.7',
 '69.2',
 '70.2',
 '13.2',
 '14.1',
 '15.1',
 '58.7',
 '94.6',
 '61.9',
 '17.6',
 '40.8',
 '287',
 '97.5',
 '79.4',
 '129.5',
 '162.6',
 '214',
 '104.8',
 '112.4',
 '80',
 '137.2',
 '101',
 '39.7',
 '96.8',
 '100.3',
 '.',
 '35.9',
 '130.8',
 '72.7',
 'm',
 '1/8',
 '65.1',
 '43.3',
 '212.7',
 '701',
 '23.2',
 '177.2',
 '76.8',
 '39.1',
 '28.1',
 '3.5',
 '148',
 '74',
 '154.9',
 '170.2',
 '101.5',
 '55.3',
 '105.5',
 '74.3',
 '27.8',
 '70.8',
 '177.8',
 '172.7',
 '204.5',
 '147.3',
 '5.86',
 '0.6',
 '84',
 '1.7',
 '235',
 '18.9',
 '46.5',
 '11.3',
 '39.2',
 '163.8',
 '176.5',
 '261.6',
 '389.3',
 '144',
 'straps',
 '17.2',
 'e',
 'socket',
 '13.9',
 '64',
 '12',
 'ear',
 '34.8',
 '38',
 '52',
 '16.1',
 'in.',
 '205.1',
 '521.7',
 '634.4',
 '123.2',
 '215.9',
 '87.9',
 '101.3',
 '2.54',
 '2',
 '1183.6',
 '111.1',
 '115.3',
 'top',
 'each',
 '34',
 '14.4',
 '24',
 '23',
 '11.2',
 '112',
 '118.4',
 '185.7',
 '.1–.71',
 'square',
 '3.1',
 '3',
 '110.8',
 '564',
 '106',
 '102.2',
 '1729.3',
 '1196.3',
 '128.4',
 '104.5',
 '104.4',
 '75.2',
 '221',
 '662.3',
 'leaves',
 '1840.2',
 '556.9',
 '55.4',
 '78.9',
 '794.7',
 '142.2',
 '146.7',
 '57',
 '1.8',
 '828',
 '1304.9',
 '663.6',
 '82.9',
 '286.5',
 '321.3',
 '107.6',
 '3.7',
 '374',
 '353.1',
 '1398.9',
 '168.3',
 '208.3',
 '593.7',
 '103.8',
 '85.7',
 '94.5',
 '33.8',
 '241.3',
 '53.8',
 '112.1',
 '92.6',
 '217.5',
 '750.6',
 '370.8',
 '152.4',
 '357.6',
 'dowel',
 '114.6',
 'saucer',
 '259.1',
 '360.7',
 '731.5',
 '91.9',
 '338.5',
 '51.3',
 '188.6',
 '934.9',
 '(4-panel',
 '490.9',
 '327.7',
 '374.7',
 '165.4',
 '285.8',
 '38.9',
 '226.1',
 '356.2',
 '371.8',
 '31.4',
 '163.2',
 '53',
 '111.4',
 '110.5',
 '388.6',
 '55.1',
 '31.5',
 '355.6',
 '15.8',
 '25.8',
 '19',
 '35.5',
 '309.2',
 '346.8',
 '377.2',
 '263.8',
 '124.5',
 '143.8',
 '135.6',
 '689.4',
 '1.5',
 '2.3',
 '27.7',
 '48.8',
 '322.9',
 '2.6',
 '2.8',
 '306.9',
 '96',
 '30.8',
 '52.2',
 '68.9',
 '31',
 '70.9',
 '45.2',
 '168.8',
 '144.8',
 '125.7',
 '487.7',
 '77.2',
 '33.1',
 '32.8',
 '23.9',
 '95.3',
 '355',
 '304.4',
 '150.2',
 '342.9',
 '346.2',
 '59.4',
 '133',
 '31.7',
 '34.5',
 '85',
 '36',
 '24.5',
 '31.3',
 'cover',
 'stand',
 '3/4',
 '29.80.2–.16',
 '70',
 '23.4',
 '360',
 '287.8',
 '334',
 '102.9',
 '165.6',
 '182.6',
 '384.3',
 '88.2',
 '28.4',
 '113.6',
 '39.5',
 '29.7',
 '34.4',
 '34.7',
 '551',
 '598.8',
 '563.2',
 '107.3',
 '206.4',
 '1096.2',
 'base',
 'hem',
 '6.0',
 '279.1',
 '645.2',
 '609.6',
 '712.2',
 '717.6',
 '527.7',
 '349.9',
 '603.3',
 '490.2',
 '688.3',
 '953.8',
 'approx.',
 '497.7',
 '431.8',
 '348',
 '402.6',
 '337.8',
 '916.3',
 '95.9',
 '202.2',
 '642.9',
 '453.1',
 '330.8',
 '374.4',
 '441.3',
 '93',
 '971.6',
 '125.1',
 '683.3',
 '33.5',
 '593.1',
 '488',
 '762',
 '156',
 '75.7',
 '55.7',
 '117.7',
 '44.7',
 '14.5',
 '29',
 '37.7',
 '290',
 '33.9',
 '51.7',
 '87',
 '367.7',
 '60.4',
 '25.9',
 '316.2',
 '39.3',
 '355.2',
 '60',
 '58',
 '41.7',
 '48',
 '54.2',
 '49.4',
 '32.2',
 '105.7',
 '95.6',
 '109.5',
 '78.4',
 '120.7',
 '624.8',
 '53.5',
 '375.9',
 '79.7',
 '83.5',
 '83.2',
 '19.5',
 '454.5',
 '41.1',
 '40.5',
 '47.8',
 '21.5',
 '41.2',
 '40.9',
 '72.4',
 '24.6',
 '11.6',
 '30.6',
 '29.6',
 '36.7',
 '28.8',
 '58.5',
 '42',
 '383.5',
 '139.7',
 '18',
 '18.3',
 '18.5',
 '18.8',
 '0.7',
 '1.2',
 '0.5',
 '17.4',
 '0.1',
 '752',
 '1354.5',
 '25.5',
 '4.2',
 '3.4',
 '3.6',
 '35.7',
 '41.4',
 '1249.7',
 '123.8',
 '617.2',
 '132.7',
 '119.4',
 '118.1',
 '114.9',
 '126.4',
 '125.4',
 '117.8',
 '132.1',
 'unfolded',
 '366.1',
 '37.1',
 '29.1',
 '29.4',
 '120',
 '98.4',
 '117.5',
 '109.9',
 '97.2',
 '113.8',
 '128.6',
 '148.3',
 '99.1',
 '161',
 '509.3',
 '507.8',
 '993.8',
 '1265.2',
 '1264.9',
 '349.4',
 '104.1',
 '5',
 '186.1',
 '143.5',
 'b',
 '134.6',
 '223.2',
 '932.2',
 '169.1',
 '354.2',
 '283.2',
 'a–j',
 '800.1',
 'k',
 '1285',
 '58.8',
 '189.5',
 '553.7',
 '21.2',
 '18.2',
 '16',
 '15.3',
 '17',
 '15',
 '19.2',
 '17.7',
 '0.3',
 '100',
 '174.6',
 'panels',
 '162.9',
 '407.7',
 '823',
 '255.3',
 '268.6',
 '140',
 '43.7',
 '56.3',
 '32.9',
 '366.4',
 '481.3',
 '38.3',
 '34.1',
 '262.9',
 '187',
 '17.3',
 '11.5',
 '22',
 '15.5',
 '13.4',
 '16.9',
 '20.5',
 '16.6',
 '16.3',
 '22.8',
 '21.1',
 '33.6',
 '12.6',
 '19.3',
 '93.7',
 '184.5',
 '141',
 '142.9',
 '274.3',
 '118.7',
 '149.2',
 '495',
 'bells',
 'a',
 '86.7',
 '315',
 '113',
 '63.8',
 '130.5',
 '200.7',
 '138.7',
 '179.7',
 '139.1',
 '457.8',
 '190.5',
 '313.1',
 '502.9',
 '167.6',
 '213.4',
 '147.6',
 '122.2',
 '127.6',
 '136.2',
 '135.3',
 '171.5',
 '194.6',
 '131.4',
 '126',
 '130.2',
 '148.9',
 '223.5',
 'neck',
 'dimensions',
 '7.0',
 '.26a',
 '51',
 'mm.',
 'earring',
 '317.5g',
 '2.08',
 'mount',
 '143.2',
 '175.9',
 '141.6',
 'finial',
 '8.5',
 '165.1',
 '157.2',
 '210.2',
 '210.8',
 '224.8',
 '92.1',
 '94.9',
 '60.0',
 '149.9',
 'approximated',
 '158.1',
 '284.5',
 '579.1',
 '248.9',
 '161.3',
 '185.4',
 '144.5',
 '144.1',
 '140.3',
 '117.2',
 '60.6',
 '67.6',
 '171.1',
 'toe',
 'tip',
 '161.9',
 '175.3',
 '217.2',
 '77.8',
 '242.6',
 '495g',
 'frame',
 '26.0',
 'confirmed',
 '198.1',
 'curve',
 '155.6',
 '61.0',
 '38.6',
 '97.8',
 '469.9',
 '80.3',
 '181.6',
 '403.9',
 '23.3',
 '33.0',
 '19.8',
 'band',
 '546.1',
 '124.1',
 '349.2697kg',
 '0.9',
 '21.4',
 '47.0',
 '203.2',
 'measurements',
 '146.1',
 '714.4153kg',
 '57.1',
 '163.5',
 '.185a',
 '24.9',
 '30',
 '2282.9g',
 '75.9',
 '151.1',
 'cross',
 'b]',
 '27.1',
 '31.9',
 '46.8',
 '24.3',
 '289.6',
 '558.8',
 '434.3',
 '350.5',
 '26.2',
 '31.6',
 '.88',
 'handles',
 '(a',
 '12.8',
 '299.7',
 'handle',
 '329.6',
 '.33',
 '.94',
 '518.2',
 '317.5',
 'width',
 '209.6',
 '279.4',
 '64.2',
 '748.0',
 'attachment',
 '66.0',
 '408.237g',
 '462.3',
 '246.4',
 '39.8',
 'dais',
 '238.8',
 '12.7.',
 'raised',
 '63.7',
 '30.3',
 '4.5',
 'only',
 '497.2',
 '529.6',
 'dome',
 '457.2',
 'forearm',
 '27.0',
 'ring',
 'case',
 'measurement',
 'erect',
 'upright',
 '56',
 '839.154g',
 '191.2',
 '264.2',
 '1005g',
 '228.6',
 '143',
 '332.1',
 'approximate',
 '81',
 '105.1',
 '635',
 '515.6',
 '320',
 '269.2',
 '330.2',
 '234.6',
 '231.8',
 ...]

In [32]:
df['hight_col'] = pd.to_numeric(df['hight_col'], errors='coerce')
df['width_col'] = pd.to_numeric(df['width_col'], errors='coerce')
df['length_col'] = pd.to_numeric(df['length_col'], errors='coerce')
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,New_Dimensions,hight_col,width_col,length_col
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477799,23.112.2893,False,False,True,860869,NaN,Drawings and Prints,1923,Drawing,Phaeton #24567,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,34.3 × 57.2,34.3,NaN,57.2
477800,23.112.2894,False,False,True,860870,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton #25538-25539 (#21222),...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33.0,NaN,56.5
477801,53.600.1434,False,False,False,860871,NaN,Drawings and Prints,1953,Print,"Forest landscape with cattle drinking, a woman...",...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,29.6 × 19.4,29.6,NaN,19.4
477802,23.112.2895,False,False,True,860872,NaN,Drawings and Prints,1923,Drawing,Phaeton with folding top,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33.0,NaN,56.5
477803,23.112.2896,False,False,True,860873,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton,...,NaN,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,29.8 × 45.1,29.8,NaN,45.1

###b)Country Column

In [33]:
#Check uniqe values on country column
df['Country'].unique().tolist()

[nan,
 'Mexico',
 'Guatemala',
 'United States',
 'England',
 'Spain',
 'United States|England',
 'Netherlands',
 'United States|United States',
 'France',
 'Canada',
 'United States|France',
 'England|France',
 'China',
 'Italy',
 'Japan',
 'Germany',
 'Netherlands|Netherlands',
 'Czech Republic',
 'England|Ireland',
 'Ireland|United States',
 'Venezuela',
 'England|Netherlands',
 'England|Belgium',
 'France|Italy',
 'Bermuda',
 'Ireland',
 'India',
 'England|United States',
 'United States|United States|United States',
 'France|NEW ZEALAND ROTORUA WHAKAREWAREWA',
 'China|NEW ZEALAND ROTORUA WHAKAREWAREWA',
 'Germany|Italy',
 'Lisez et propagez nos Annales: "L\'Immacul‚e"',
 'France|Bernard Turner',
 'France|Harold Copping',
 'Czech Republic|England',
 'Belgium|France',
 'Belgium|England|France',
 'United States|Germany',
 'France|Germany',
 'Scotland',
 'Germany|Czech Republic',
 'Holland',
 'England|England',
 'United States|Denmark',
 'Finland|Denmark|United States',
 'United States|China',
 'China|India',
 'United States|Wales',
 'Italy|United States',
 'United States|England|Scotland|Wales',
 'Switzerland',
 'Portugal',
 'Scotland or England',
 'England|Scotland',
 'Paraguay',
 'United States|United States|United States|United States',
 'France|Switzerland',
 'United States|France|Tibet',
 'Iran',
 'Russia',
 'Turkey',
 'United States|British Isles',
 'Germany|Netherlands',
 'United States|India',
 'France|England',
 'United States|Italy',
 'Peru',
 'Colombia',
 'Syria',
 'Democratic Republic of the Congo',
 'Cameroon',
 'Armenia',
 'possibly from the Balkans',
 'Algeria',
 'Algeria or Morocco',
 'Palestine',
 'Morocco',
 'Uzbekistan',
 'South Africa',
 'Kuwait',
 'Samoa',
 'Tonga',
 'Tonga or Samoa',
 'present-day Uzbekistan',
 'Burkina Faso',
 'Afghanistan',
 'Nigeria',
 'probably Afghanistan',
 'present-day Afghanistan',
 'Pakistan',
 'probably from the Balkans',
 'probably Balkans or Anatolia',
 'Turkmenistan',
 'Ghana',
 "Côte d'Ivoire",
 'Kenya',
 'Ethiopia',
 'Tanzania',
 'Tanzania or Kenya',
 'Madagascar',
 'Liberia',
 'Morocco or Algeria',
 'probably Morocco',
 'probably Algeria',
 'Tunesia',
 'Tunisia',
 'TunIsia',
 'Egypt',
 'probably Egypt',
 'Indonesia',
 'Java',
 'Borneo',
 'Philippines',
 'probably Iran',
 'probably Syria',
 'Syria or Palestine',
 'Saudi Arabia',
 'Palestine or Syria',
 'Iraq',
 'probably Georgia',
 'Panama',
 'Saudi Arabia or Yemen',
 'probably Turkey',
 'United States(?)',
 'Georgia',
 'Turkey or the Balkans',
 'Egypt or Syria',
 'Bolivia',
 'iran',
 'probably iran',
 'Uganda',
 'Brazil|Portugal',
 'China|Mexico',
 'Spain|Mexico',
 'Italy|France',
 'Flanders|Mexico',
 'Spain|Germany|Mexico',
 'Mexico|China',
 'Ecuador|Peru',
 'Guatemala|Mexico',
 'Ecuador|Philippines',
 'Ecuador|Ecuador',
 'Peru|Ecuador',
 'Ecuador',
 'Mexico|Ecuador',
 'Mexico|Guatemala',
 'Cuba',
 'Brazil',
 'Ecuador|Mexico',
 'Papua New Guinea',
 'Costa Rica or Panama',
 'Colombia (?)',
 'Philippines (?)',
 'Chile',
 'Peru or Bolivia',
 'Costa Rica|Costa Rica',
 'Costa Rica',
 'Argentina',
 'Ecuador, Peru, Bolivia, Argentina, or Chile',
 'Australia',
 'Mali or Ghana',
 'Mali',
 'Solomon Islands',
 'Honduras',
 'South Sudan',
 'Ecuador, Peru, Bolivia, Chile, or Argentina',
 'Colombia or Ecuador',
 'Vanuatu',
 'Angola or Democratic Republic of the Congo',
 'Togo',
 "Côte d'Ivoire or Ghana",
 'Peru (?)',
 'Ecuador (?)',
 'Costa Rica (?)',
 "Côte d'Ivoire or Liberia",
 'Sudan',
 'Guatemala or Mexico',
 'Fiji',
 'Gabon',
 'Angola',
 'Sierra Leone',
 'Republic of Palau',
 'Bolivia or Peru',
 'Suriname',
 'Gabon or Republic of the Congo',
 'Guinea',
 'Gabon or Republic of Congo',
 'Rwanda',
 'Zambia',
 'Republic of Congo',
 "Burkina Faso or Côte d'Ivoire or Mali",
 'Republic of Benin',
 "Côte d'Ivoire or Burkina Faso",
 'Central African Republic',
 "Guinea or Mali or Burkina Faso or Côte d'Ivoire",
 'Gabon or Equatorial Guinea',
 'Republic of the Congo',
 'Nigeria (?)',
 'Democratic Republic of the Congo, Republic of the Congo, or Cabinda, Angola',
 'Republic of Guinea-Bissau',
 'Democratic Republic of the Congo|Cabinda, Angola|Republic of the Congo',
 'Cameroon or Nigeria',
 'Kenya or Tanzania',
 'French Polynesia',
 'New Zealand',
 'Australia or Papua New Guinea',
 'New Caledonia',
 'Republic of the Marshall Islands',
 'Marquesas Islands',
 'Tahiti',
 'Austria',
 'Togo or Ghana (possibly Kpandu)',
 'Chad',
 'Somalia',
 'Unknown country',
 "Mali or Côte d'Ivoire",
 'Costa Rica or Nicaragua',
 'Dominican Republic (?)',
 'Ecuador or Colombia',
 'French Guiana',
 'Puerto Rico',
 'Mexico (?)',
 'Brazil (?)',
 'United States or Canada',
 'Mexico or Guatemala',
 'Dominican Republic',
 'Cook Islands',
 'Federated States of Micronesia',
 'Mangareva',
 'Wallis and Futuna Territory',
 'Liberia or Guinea',
 'Burkina Faso or Ghana',
 "Côte d'Ivoire or Ghana (?)",
 'Nauru',
 'Malawi',
 'Republic of Benin or Togo',
 'El Salvador or Guatemala',
 "Côte d'Ivoire or Mali",
 'Ghana (?)',
 'Republic of Kiribati',
 'Republic of Kiribati (?)',
 "Burkina Faso or Côte d'Ivoire",
 'Zimbabwe',
 'Coastal Ecuador',
 'Democratic Republic of Timor-Leste',
 'Taiwan',
 'Malaysia',
 'Vietnam',
 'Chile or Peru',
 'Nigeria or Republic of Benin',
 'Nigeria (made in England)',
 'Nigeria (made in Western Europe)',
 'Ecuador or Peru',
 'Niger',
 'South Africa or Swaziland',
 'Bolivia (?)',
 'Peru or Chile',
 'El Salvador',
 'United States (?)',
 'Guatemala (?)',
 'Mali or Niger',
 'South Africa or Mozambique',
 'Laos',
 'Democratic Republic of the Congo|Republic of the Congo|Angola',
 'Democratic Republic of the Congo|Angola|Republic of the Congo',
 'Democratic Republic of the Congo or Angola',
 'Tanzania or Mozambique',
 "Cote d'Ivoire",
 'Namibia',
 'Papua New Guinea, Prince Alexander Mountains',
 'Indonesia or Malaysia',
 'Nicaragua',
 'Republic of Timor-Leste',
 'Sierra Leone or Mali',
 'Zimbabwe or Mozambique',
 'Canada or United States',
 'Greenland',
 'Nigeria or Niger',
 'Peru or Ecuador',
 'Papua New Guinea|Papua New Guinea',
 'Papua New Guinea or Indonesia',
 'Republic of Benin (?)',
 'Rwanda or Burundi',
 'Togo or Ghana',
 'Republic of the Congo or Cabinda, Angola',
 'Colombia or Panama',
 'Senegal',
 'Democratic Republic of Congo',
 'Guinea Bissau',
 'South Africa or Kingdom of Swaziland',
 'Zanzibar',
 'India (?)',
 'Northern Tanzania and Kenya',
 'New Guinea',
 'Egypt and Sudan',
 'Iraq or Syria',
 'Iran or Turkey',
 'Unknown',
 'present-day Greece',
 'Greece',
 'Bulgaria',
 'Bosnia',
 'probably Greece',
 'Hungary',
 'Northern Iraq or Western Iran',
 'Turkey or Iran',
 'present-day Pakistan',
 'Syria|Egypt',
 'probably Spain',
 'Yemen',
 'Albania',
 'probably Egypt or Syria',
 'Western Iran, Northern Iraq, or Northern Syria',
 'Northern Iraq or Western Iran|Afghanistan',
 'Iran or Syria',
 'Egypt or Turkey',
 'China or present-day Uzbekistan',
 'India or Nepal',
 'Iran or Central Asia',
 'Northern Iraq, Syria, or southeastern Turkey',
 'probably Syria or northern Iraq',
 'Iran or Iraq',
 'India or Iran',
 'Syria or Iraq',
 'Southern India',
 'present-day Saudi Arabia',
 'probably Uzbekistan',
 'Balkans or Turkey',
 'probably Cyprus or Turkey',
 'Iran or Northern India',
 'Sri Lanka',
 'probably India',
 'Northern India',
 'Iran or Italy',
 'Syria or Egypt',
 'India or Turkey',
 'Iraq or Iran',
 'Iran (modern Afghanistan)',
 'Present-day Pakistan',
 'Afghanistan or Turkmenistan',
 'Central India or Rajasthan',
 'Iraq or Syria|Egypt',
 'Spain|Egypt',
 'Egypt or Syria|Egypt',
 'Spain or North Africa',
 'probably Iraq',
 'Azerbaijan',
 'present-day Israel',
 'Iran or Azerbaijan',
 'Syria or Turkey',
 'Northwestern Iran',
 'Poland',
 'Iran|Iran',
 'probably India or Iran',
 'Egypt or Palestine',
 'Bulgaria or Romania',
 'Eastern India',
 'present-day Bangladesh',
 'Iraq or Northern Jazira',
 'Northern India or Pakistan',
 'Northern Iran',
 'India or Pakistan',
 'India or present-day Pakistan',
 'Central India',
 'probably Central India',
 'Central or Southern India or Sri Lanka',
 'Central or Southern India or Sri lanka',
 'present-day Turkey',
 'Southern Italy',
 'possibly Syria or Europe',
 'possibly France',
 'probably present-day Israel',
 'probably Central Iran',
 'India, Nepal or Tibet',
 'probably Northern India',
 'Egypt, Iran or Syria',
 'present-day Azerbaijan',
 'Western Turkey',
 'Western Iran',
 'present-day China',
 'Turkmenistan or Iran',
 'Uzbekistan or Turkmenistan',
 'present-day Afghanistan or Turkmenistan',
 'Western Turkmenistan',
 'probably west-central Turkey',
 'Northwestern Iran or Transcaucasia',
 'Iran or India',
 'probably Western Turkey',
 'West Turkey',
 'Probably West Central Turkey',
 'China|Iraq',
 'possibly Iran or Egypt',
 'Syria|Iran',
 'France or India',
 'Iran or Caucasus',
 'Egypt or Iraq',
 'Western India',
 'Eastern Iran or present-day Afghanistan',
 'Greece or Turkey',
 'Possibly Syria',
 'Northwestern Iran or Kurdistan',
 'India|Egypt',
 'Iraq|Iran',
 'Eastern Iran or Khurasan',
 'Iraq|Iraq',
 'Eastern Iran',
 'probably China|Iraq',
 'Italy or Turkey',
 'Iran|Iran or Central Asia',
 'Iran or Afghanistan',
 'Iran|Iran or Uzbekistan',
 'Iran|Iraq',
 'Iran|China',
 'Iran|Iraq or western Iran',
 'Iran|present-day Uzbekistan',
 'Iran|probably Iran',
 'present-day Lebanon',
 'Iran|Iran or present-day Uzbekistan',
 'Iran|Syria or Iraq',
 'Northeastern Iran',
 'Eastern Iran or Afghanistan',
 'Armenia or Turkey',
 'Iran, Iraq, or Egypt',
 'Eastern Turkmenistan or Uzbekistan',
 'Saudi Arabia or Oman',
 'modern-day Afghanistan',
 'probably Yemen',
 'Iran or present-day Uzbekistan',
 'probably Syria or Iraq',
 'Turkey or Iraq',
 'Northwestern India',
 'Northwestern Iran, probably',
 'Central or Northern Iran',
 'Present-day Uzbekistan',
 'Northwestern Iran or Baghdad',
 'probably Northeastern Iran',
 'probably Iran or Iraq',
 'present-day Afghanistan or Central Asia',
 'probably Iraq or Syria',
 'Iran or present-day Turkmenistan',
 'Jazira (or Iran?)',
 'Jordan',
 'present-day Afghanistan or Italy',
 'Germany|Iran',
 'The Netherlands',
 'Italy or the Netherlands',
 'Northwestern Iran or Caucasus',
 'probably Iran or Turkey',
 'probably Western Iran',
 'Eastern Islamic lands',
 'Western Islamic Lands',
 'Central Asia',
 'probably the Netherlands',
 'Egypt, Iraq or Syria',
 'Iran|Egypt',
 'Northwest Turkey',
 'probably Central Turkey',
 'Central Turkey',
 'Sothern Turkmenistan',
 'present-day Uzbekistan|present-day Afghanistan',
 'present-day Uzbekistan and Afghanistan',
 'possibly Egypt',
 'Probably Egypt',
 'probably Western India',
 'Northwestern Iran or Turkey',
 'Egypt or Iran',
 'possibly Syria',
 'Probably Iran',
 'Indiaal',
 'probably Tunesia',
 'probably Tunesia or Turkey',
 'Northern or Central India',
 'India|present-day Afghanistan or Iran',
 'Northern or Western India',
 'Iran, Syria or Turkey',
 'possibly Morocco',
 'Central Asia or Iran',
 'Northern India or Deccan',
 'Present-day Turkmenistan',
 'Western Iran or Northern Iraq',
 'Iraq or Turkey',
 'Probably Iraq',
 'Egypt|Iraq or Iran',
 'india',
 'Central India or Sri Lanka',
 'possibly Iran',
 'possibly Turkey',
 'China|Iran',
 'Syria or North Africa',
 'Morocco or Southern Spain',
 'Eastern islamic lands',
 'Afghanistan or Iran',
 'Iran|present-day Afghanistan',
 'India or Sri Lanka',
 'possibly Afghanistan',
 'Egypt|Egypt',
 'Afghanistan or Northeastern Iran',
 'Syria or Iran',
 'Modern cast of 39.40.39a',
 'USA',
 'Egypt possibly (modern)',
 'Egypt possibly',
 'U.S.A.',
 'Bohemia',
 'Italy (?)',
 'Northern Italy',
 'Italy?',
 'Byzantine Egypt',
 'Europe',
 'Nicomedia',
 'Central Italy',
 'Flanders',
 'Spain (?) (setting)',
 'Tirana',
 'France or Germany',
 'southern Italy',
 'Norway',
 'Northern Adriatic',
 'France or Western Europe',
 'France or Netherlands',
 'North France',
 'France or North Spain',
 'North France or South Netherlands',
 'North Africa (box)|Spain (lid)',
 'northern France',
 'Netherlands or France',
 'Germany or the Netherlands',
 'Eastern Mediterranean',
 'south central France',
 'South France',
 'Sweden',
 'French',
 'Spain or Limoges, France',
 'France (?)',
 'Northern France',
 'northern France or western Germany',
 'Russian|Northern France',
 'La Tène II',
 'Northern France (?)',
 'probably northern France',
 'probably northern Italy',
 'Western France',
 'Gaul',
 'Alamania|Northern France',
 'Alamania',
 'Alamania|France',
 'Northern France|Alamania',
 'Niederbreisig',
 'Western Germany',
 'Rhein',
 'Alamania|Northern France|Germany',
 'Northern France|Germany',
 'Germany|Northern France',
 'southern Germany or Switzerland',
 'South Netherlands',
 'Italian',
 'Scandinavia',
 'Gotland',
 'Central Europe',
 'present-day France',
 'Egypt or Syria (?)',
 'England (possibly)',
 'the Iberian peninsula (Spain)',
 'Iberian Peninsula',
 'Germany (?)',
 'central Europe',
 'northern Europe',
 'Spain or France',
 'Southern France',
 'nothern Spain or southern France',
 'Southwestern France',
 'Belgium',
 'probably North Africa',
 'present-day Spain',
 'perhaps Syria',
 'German',
 'Germany or Netherlands',
 'France (cartoon)|Southern Netherlands (woven)',
 'Southern Netherlands (woven)|France (cartoon)',
 'Spain or|Central Italy',
 'French|Belgium',
 'France (probably)',
 'Byzantium or Spain',
 'Brussels',
 'Austria (possibly)',
 'north or central Syria',
 'possibly southern England',
 'possibly Gaul',
 'Rome',
 'Italy or present-day Spain',
 'Northern Switzerland',
 'Central or Southern Italian',
 'European',
 'Germany or France',
 'Northern Switzerland (?)',
 'Austrian',
 'Lake Van region, Vaspurakan (now eastern Turkey)',
 'Syria (?)',
 'Germany (present day France)',
 'Northeastern France',
 'Gaul (France)',
 'Northeast Italy',
 'Spain and Italy',
 'Italy (North)',
 'Ukraine',
 'Black Sea',
 'probably Italy',
 'italy',
 'North Netherlands',
 'North Netherland',
 'Germany or South Germany',
 'Austria (mounts)',
 'Lower Austria',
 'France or England',
 'Germany (present-day France)',
 'Constantinople',
 'South Italy',
 'probably British Isles',
 'South Netherland',
 'Northern Europe',
 'England or Scandinavia',
 'South Netherlandish',
 'France or Spain',
 'France|France',
 'Haute Garonne.',
 'Austria?',
 'the Netherlands',
 'Southern Netherlands',
 'Austria (now Italy, Trentino-Alto Adige)',
 'England or Meaux, France',
 'Carpathian Basin region',
 'east-central Europe',
 'Greece or the Balkans (possibly)',
 'Probably Gaul',
 'Bulgaria (possibly)',
 'probably Greece or Constantinople',
 'Southern Russia or Black Sea Region (?)',
 'possibly Hungary',
 'present-day Poland',
 'Scandinavia (possibly Sweden)',
 'France or Southern Netherlands',
 'Crete ?',
 'America',
 'UK',
 'US',
 'South Africa, Africa',
 'Italy and United States',
 'United Kingdom?',
 'United Kingdom',
 'China or Mongolia',
 'Japan|China',
 'Tibet',
 'China or Japan',
 'Korea',
 'India|Nepal',
 'Myanmar (formerly Burma)',
 'Thailand',
 'Thailand and Myanmar (formerly Burma)',
 'Myanmar',
 'Croatia',
 'Spain or Yugoslavia',
 'Ghana or Nigeria',
 'Borneo or China?',
 'United States or Mexico: N.A.',
 'Venezuela:N.A.',
 'Germany?',
 'United States?',
 'Iran (Persia)',
 'Russia Federation',
 'Russian Federation',
 'Georgia, Republic of  [Azerbaijan, Armenia]',
 'Azerbaijan, Armenia or Georgia',
 'Arabia|Iran',
 'Montenegro?  Yugoslavia (former)',
 'Morocco?',
 'Turkey? (old cat. Arabia)',
 'Arabia',
 'India?',
 'Syria?',
 'Arabian Peninsula',
 'Syria?  Saudia Arabia',
 'Sudan?',
 'Egypt, Bulgaria or Turkey?',
 'Bulgaria|Egypt',
 'Egypt?',
 'Bulgaria?',
 'former Yugoslavia',
 'Democratic Republic of the Congo?',
 'possibly Dem. Rep. of Congo',
 'Congo',
 'Mozambique',
 'Senegal or Gambia',
 'Congo?',
 'Benin or Gabon',
 'Benin',
 'Algeria?',
 'probably South Africa',
 'Spain?',
 'probably Ethiopia',
 'Republic of Cameroon',
 'Canada: N.A.',
 'Mexico?',
 'possibly Guyana',
 'Costa Rica?',
 'Belgium?',
 'Guyana',
 'Guatemala|Guyana',
 'United States or Brazil',
 'Brazil?',
 'Colombia|Ecuador',
 'New Zealand?',
 'New Guinea (Phillipine?)',
 'Marshall Islands',
 'Possibly Sarawak',
 'Sarawak',
 'Italy or France',
 'former Yugoslavia(?)',
 'Romania?',
 'France?',
 'Switzerland?',
 'United Kingdom or Germany',
 'Slovakia',
 'Germany, France, or Bohemia',
 'United States or Germany ?',
 'Greece?',
 'Austria or Germany',
 'Finland',
 'Portugal?',
 'Netherlands?',
 'Friesland',
 'possibly Germany',
 'Italian?',
 'possibly Madagascar',
 'Probably Sierra Leone',
 'Cameroon?',
 'Sierra Leone?',
 'Germany or Switzerland',
 'Arabia or North Africa',
 'Uganda or Kenya',
 'Republic of Cameroon or Gabon?',
 'Italy or Germany?',
 'Norfolk Island',
 'Turkey or Greece?',
 'Italy or Sicily',
 'Madagascar?',
 'Sulawesi (Celebes)',
 'Czech Republic (Bohemia)',
 'Senegal?',
 'Belgium or France',
 'Gabon?',
 'Germany or England',
 'Egypt (British repro)',
 'Uganda/Tanzania',
 'Mozambique|Zimbabwe|Malawi',
 'France or Belgium',
 'Peru|Peru',
 "Liberia-Côte d'Ivoire (Ivory Coast) border",
 'United States or Canada: N.A.',
 'Germany or France?',
 'Ghana?',
 'Germany or Belgium',
 'Peru?',
 'Bosnia and Herzegovina (former Yugoslavia)',
 'Iran (Persia) and Turkey',
 'Nigeria or Benin',
 'France or Italy',
 'Russia?',
 'China?',
 'Japan or China',
 'Gambia',
 'Turkey?',
 'Montenegro',
 'Japan or Korea',
 'Uganda/Rwanda',
 'Iran?',
 'Malta',
 'Republic of Costa Rica',
 'United States or Mexico',
 'Uganda?',
 'Colombia or Costa Rica',
 'Nigeria?',
 'Nepal?',
 'France:N.',
 'China or Korea',
 'Burkina Faso (formerly Upper Volta)',
 'Democratic Republic of the Congo or Angola?',
 'Ivory Coast',
 'Nepal',
 'Sumatra',
 'Ghana or Senegal',
 'Nigeria or Congo',
 'Probably Burkina Faso',
 'Papua New Guinea?',
 'Lesotho',
 'Tajikistan',
 'Czechoslovakia or Germany?',
 'United Kingdom or France?',
 'Nigeria, Ghana or Sierra Leone',
 'Serbia',
 'Ireland or United Kingdom',
 'Nigeria or Cameroon',
 'Mongolia',
 'France?/USA?',
 'France|United States',
 'Flemish',
 'Republic of Guinea',
 'Uzbekistan or Tajikistan',
 'Malawi or Tanzania',
 'Greece|Turkey',
 'Probably Democratic Republic of Congo',
 'Tibet|China|India',
 'Cambodia',
 'Colombia or Venezuela',
 'United Kingdom or France',
 'Hungary or Slovenia',
 'Austria / Germany',
 'Germany (probably)',
 'Mauritania',
 'Colombia?',
 'Republic of  Cameroon',
 'Chad?',
 'Republic of Cameroon?',
 'Liberia?',
 'Kosova',
 'probably Germany',
 'Tibet/north India',
 'Indonesia?',
 'Thailand?',
 'Probably Democratic Republic of the Congo',
 'Bhutan',
 'Mozambique?',
 'Germany or Austria',
 'Denmark',
 'Germany or Italy?',
 'England?',
 'Croatia (former Yugoslavia)',
 'Zambia or Zimbabwe',
 'United States|Austria',
 'Uganda-Sudan',
 'Mongolia?',
 'Burma?',
 'Uganda or Democratic Republic of Congo',
 'Tanzania/Kenya',
 'Macedonia',
 'Slovenia',
 'United States or Germany',
 'Republic of Congo & Angola',
 'Philippine Islands',
 'Italy or Germany',
 'Germany or Italy',
 'Macedonia (former Yugoslavia)',
 'United Kingdom ?',
 'Republic of the Philippines',
 'Norway or Sweden',
 'England|Germany',
 'Germany or Poland',
 'India (north)',
 'Netherlands or Belgium',
 'Zambia?',
 'Myanmar (Burma)',
 'Bulgaria or Switzerland',
 'Myanmar (Burmah) or Thai',
 'Sulawesi',
 'Tibet|China',
 'Serbia (former Yugoslavia)',
 'Bosnia (former Yugoslavia)',
 'Herzegovina (former Yugoslavia)',
 'Bosnia - Herzegovina (former Yugoslavia)',
 'Possibly Greece',
 'Scandinavia or Austria',
 'Ireland ?',
 'Austria ?',
 'Belgium ?',
 'possibly Dem. Rep. Congo',
 'Norway?',
 'India|Pakistan',
 'Azerbaijan?',
 'Malaysia?',
 'Turkey or Azerbaijan',
 'Bohemia|Germany|Italy',
 'Bohemia (Hungary)',
 'Laos and Thailand',
 'possibly Guatemala',
 'Persia or Turkey',
 'Probably Germany',
 'Tibet/Nepal?',
 'Myanmar (Burma) or Thailand',
 'Switzerland|France',
 'Republic of Madagascar',
 'possibly Mali|Possibly Algeria/Tunesia',
 'England or Germany',
 'Ethiopia or Sudan',
 'Pakistan|India',
 'Dem. Rep. Congo',
 'Czech Republic or Slovakia',
 'Italy|United Kingdom',
 'Turkey|India',
 'Canaan',
 'Cyprus',

In [34]:
#Function to clean the country column 
def clean_country(country):
    if isinstance(country, str):
        country = country.strip()  # Remove leading/trailing whitespaces
        country = country.title()  # Capitalize the first letter of each word
        country = country.replace(' Or ', ' , ')  # Replace ' or ' with ','
        country = country.replace('|', ' , ')  # Replace ' | ' with ','
        country = country.replace('Present-Day ', '')  # Remove 'Present-Day ' prefix
        country = country.replace('Probably ', '')  # Remove 'Probably ' prefix
        country = country.replace('Possibly ', '')  # Remove 'Possibly ' prefix
        country = country.replace('Unknown Country', 'null')  # Replace 'Unknown Country' with NaN
        country = country.replace('?', '')  # Remove '?' if present
        country = country.replace('()', '')  # Remove '()' if present

    return country

In [35]:
#Apply Function one our DF
df['New_Country'] = df['Country'].apply(clean_country)

In [36]:
df['New_Country'].unique().tolist()

[nan,
 'Mexico',
 'Guatemala',
 'United States',
 'England',
 'Spain',
 'United States , England',
 'Netherlands',
 'United States , United States',
 'France',
 'Canada',
 'United States , France',
 'England , France',
 'China',
 'Italy',
 'Japan',
 'Germany',
 'Netherlands , Netherlands',
 'Czech Republic',
 'England , Ireland',
 'Ireland , United States',
 'Venezuela',
 'England , Netherlands',
 'England , Belgium',
 'France , Italy',
 'Bermuda',
 'Ireland',
 'India',
 'England , United States',
 'United States , United States , United States',
 'France , New Zealand Rotorua Whakarewarewa',
 'China , New Zealand Rotorua Whakarewarewa',
 'Germany , Italy',
 'Lisez Et Propagez Nos Annales: "L\'Immacul‚E"',
 'France , Bernard Turner',
 'France , Harold Copping',
 'Czech Republic , England',
 'Belgium , France',
 'Belgium , England , France',
 'United States , Germany',
 'France , Germany',
 'Scotland',
 'Germany , Czech Republic',
 'Holland',
 'England , England',
 'United States , Denmark',
 'Finland , Denmark , United States',
 'United States , China',
 'China , India',
 'United States , Wales',
 'Italy , United States',
 'United States , England , Scotland , Wales',
 'Switzerland',
 'Portugal',
 'Scotland , England',
 'England , Scotland',
 'Paraguay',
 'United States , United States , United States , United States',
 'France , Switzerland',
 'United States , France , Tibet',
 'Iran',
 'Russia',
 'Turkey',
 'United States , British Isles',
 'Germany , Netherlands',
 'United States , India',
 'France , England',
 'United States , Italy',
 'Peru',
 'Colombia',
 'Syria',
 'Democratic Republic Of The Congo',
 'Cameroon',
 'Armenia',
 'From The Balkans',
 'Algeria',
 'Algeria , Morocco',
 'Palestine',
 'Morocco',
 'Uzbekistan',
 'South Africa',
 'Kuwait',
 'Samoa',
 'Tonga',
 'Tonga , Samoa',
 'Burkina Faso',
 'Afghanistan',
 'Nigeria',
 'Pakistan',
 'Balkans , Anatolia',
 'Turkmenistan',
 'Ghana',
 "Côte D'Ivoire",
 'Kenya',
 'Ethiopia',
 'Tanzania',
 'Tanzania , Kenya',
 'Madagascar',
 'Liberia',
 'Morocco , Algeria',
 'Tunesia',
 'Tunisia',
 'Egypt',
 'Indonesia',
 'Java',
 'Borneo',
 'Philippines',
 'Syria , Palestine',
 'Saudi Arabia',
 'Palestine , Syria',
 'Iraq',
 'Georgia',
 'Panama',
 'Saudi Arabia , Yemen',
 'Turkey , The Balkans',
 'Egypt , Syria',
 'Bolivia',
 'Uganda',
 'Brazil , Portugal',
 'China , Mexico',
 'Spain , Mexico',
 'Italy , France',
 'Flanders , Mexico',
 'Spain , Germany , Mexico',
 'Mexico , China',
 'Ecuador , Peru',
 'Guatemala , Mexico',
 'Ecuador , Philippines',
 'Ecuador , Ecuador',
 'Peru , Ecuador',
 'Ecuador',
 'Mexico , Ecuador',
 'Mexico , Guatemala',
 'Cuba',
 'Brazil',
 'Ecuador , Mexico',
 'Papua New Guinea',
 'Costa Rica , Panama',
 'Colombia ',
 'Philippines ',
 'Chile',
 'Peru , Bolivia',
 'Costa Rica , Costa Rica',
 'Costa Rica',
 'Argentina',
 'Ecuador, Peru, Bolivia, Argentina, , Chile',
 'Australia',
 'Mali , Ghana',
 'Mali',
 'Solomon Islands',
 'Honduras',
 'South Sudan',
 'Ecuador, Peru, Bolivia, Chile, , Argentina',
 'Colombia , Ecuador',
 'Vanuatu',
 'Angola , Democratic Republic Of The Congo',
 'Togo',
 "Côte D'Ivoire , Ghana",
 'Peru ',
 'Ecuador ',
 'Costa Rica ',
 "Côte D'Ivoire , Liberia",
 'Sudan',
 'Fiji',
 'Gabon',
 'Angola',
 'Sierra Leone',
 'Republic Of Palau',
 'Bolivia , Peru',
 'Suriname',
 'Gabon , Republic Of The Congo',
 'Guinea',
 'Gabon , Republic Of Congo',
 'Rwanda',
 'Zambia',
 'Republic Of Congo',
 "Burkina Faso , Côte D'Ivoire , Mali",
 'Republic Of Benin',
 "Côte D'Ivoire , Burkina Faso",
 'Central African Republic',
 "Guinea , Mali , Burkina Faso , Côte D'Ivoire",
 'Gabon , Equatorial Guinea',
 'Republic Of The Congo',
 'Nigeria ',
 'Democratic Republic Of The Congo, Republic Of The Congo, , Cabinda, Angola',
 'Republic Of Guinea-Bissau',
 'Democratic Republic Of The Congo , Cabinda, Angola , Republic Of The Congo',
 'Cameroon , Nigeria',
 'Kenya , Tanzania',
 'French Polynesia',
 'New Zealand',
 'Australia , Papua New Guinea',
 'New Caledonia',
 'Republic Of The Marshall Islands',
 'Marquesas Islands',
 'Tahiti',
 'Austria',
 'Togo , Ghana (Kpandu)',
 'Chad',
 'Somalia',
 'null',
 "Mali , Côte D'Ivoire",
 'Costa Rica , Nicaragua',
 'Dominican Republic ',
 'Ecuador , Colombia',
 'French Guiana',
 'Puerto Rico',
 'Mexico ',
 'Brazil ',
 'United States , Canada',
 'Dominican Republic',
 'Cook Islands',
 'Federated States Of Micronesia',
 'Mangareva',
 'Wallis And Futuna Territory',
 'Liberia , Guinea',
 'Burkina Faso , Ghana',
 "Côte D'Ivoire , Ghana ",
 'Nauru',
 'Malawi',
 'Republic Of Benin , Togo',
 'El Salvador , Guatemala',
 "Côte D'Ivoire , Mali",
 'Ghana ',
 'Republic Of Kiribati',
 'Republic Of Kiribati ',
 "Burkina Faso , Côte D'Ivoire",
 'Zimbabwe',
 'Coastal Ecuador',
 'Democratic Republic Of Timor-Leste',
 'Taiwan',
 'Malaysia',
 'Vietnam',
 'Chile , Peru',
 'Nigeria , Republic Of Benin',
 'Nigeria (Made In England)',
 'Nigeria (Made In Western Europe)',
 'Niger',
 'South Africa , Swaziland',
 'Bolivia ',
 'Peru , Chile',
 'El Salvador',
 'United States ',
 'Guatemala ',
 'Mali , Niger',
 'South Africa , Mozambique',
 'Laos',
 'Democratic Republic Of The Congo , Republic Of The Congo , Angola',
 'Democratic Republic Of The Congo , Angola , Republic Of The Congo',
 'Democratic Republic Of The Congo , Angola',
 'Tanzania , Mozambique',
 "Cote D'Ivoire",
 'Namibia',
 'Papua New Guinea, Prince Alexander Mountains',
 'Indonesia , Malaysia',
 'Nicaragua',
 'Republic Of Timor-Leste',
 'Sierra Leone , Mali',
 'Zimbabwe , Mozambique',
 'Canada , United States',
 'Greenland',
 'Nigeria , Niger',
 'Papua New Guinea , Papua New Guinea',
 'Papua New Guinea , Indonesia',
 'Republic Of Benin ',
 'Rwanda , Burundi',
 'Togo , Ghana',
 'Republic Of The Congo , Cabinda, Angola',
 'Colombia , Panama',
 'Senegal',
 'Democratic Republic Of Congo',
 'Guinea Bissau',
 'South Africa , Kingdom Of Swaziland',
 'Zanzibar',
 'India ',
 'Northern Tanzania And Kenya',
 'New Guinea',
 'Egypt And Sudan',
 'Iraq , Syria',
 'Iran , Turkey',
 'Unknown',
 'Greece',
 'Bulgaria',
 'Bosnia',
 'Hungary',
 'Northern Iraq , Western Iran',
 'Turkey , Iran',
 'Syria , Egypt',
 'Yemen',
 'Albania',
 'Western Iran, Northern Iraq, , Northern Syria',
 'Northern Iraq , Western Iran , Afghanistan',
 'Iran , Syria',
 'Egypt , Turkey',
 'China , Uzbekistan',
 'India , Nepal',
 'Iran , Central Asia',
 'Northern Iraq, Syria, , Southeastern Turkey',
 'Syria , Northern Iraq',
 'Iran , Iraq',
 'India , Iran',
 'Syria , Iraq',
 'Southern India',
 'Balkans , Turkey',
 'Cyprus , Turkey',
 'Iran , Northern India',
 'Sri Lanka',
 'Northern India',
 'Iran , Italy',
 'India , Turkey',
 'Iraq , Iran',
 'Iran (Modern Afghanistan)',
 'Afghanistan , Turkmenistan',
 'Central India , Rajasthan',
 'Iraq , Syria , Egypt',
 'Spain , Egypt',
 'Egypt , Syria , Egypt',
 'Spain , North Africa',
 'Azerbaijan',
 'Israel',
 'Iran , Azerbaijan',
 'Syria , Turkey',
 'Northwestern Iran',
 'Poland',
 'Iran , Iran',
 'Egypt , Palestine',
 'Bulgaria , Romania',
 'Eastern India',
 'Bangladesh',
 'Iraq , Northern Jazira',
 'Northern India , Pakistan',
 'Northern Iran',
 'India , Pakistan',
 'Central India',
 'Central , Southern India , Sri Lanka',
 'Southern Italy',
 'Syria , Europe',
 'Central Iran',
 'India, Nepal , Tibet',
 'Egypt, Iran , Syria',
 'Western Turkey',
 'Western Iran',
 'Turkmenistan , Iran',
 'Uzbekistan , Turkmenistan',
 'Western Turkmenistan',
 'West-Central Turkey',
 'Northwestern Iran , Transcaucasia',
 'Iran , India',
 'West Turkey',
 'West Central Turkey',
 'China , Iraq',
 'Iran , Egypt',
 'Syria , Iran',
 'France , India',
 'Iran , Caucasus',
 'Egypt , Iraq',
 'Western India',
 'Eastern Iran , Afghanistan',
 'Greece , Turkey',
 'Northwestern Iran , Kurdistan',
 'India , Egypt',
 'Eastern Iran , Khurasan',
 'Iraq , Iraq',
 'Eastern Iran',
 'Italy , Turkey',
 'Iran , Iran , Central Asia',
 'Iran , Afghanistan',
 'Iran , Iran , Uzbekistan',
 'Iran , China',
 'Iran , Iraq , Western Iran',
 'Iran , Uzbekistan',
 'Lebanon',
 'Iran , Syria , Iraq',
 'Northeastern Iran',
 'Armenia , Turkey',
 'Iran, Iraq, , Egypt',
 'Eastern Turkmenistan , Uzbekistan',
 'Saudi Arabia , Oman',
 'Modern-Day Afghanistan',
 'Turkey , Iraq',
 'Northwestern India',
 'Northwestern Iran, Probably',
 'Central , Northern Iran',
 'Northwestern Iran , Baghdad',
 'Afghanistan , Central Asia',
 'Iran , Turkmenistan',
 'Jazira (Or Iran)',
 'Jordan',
 'Afghanistan , Italy',
 'Germany , Iran',
 'The Netherlands',
 'Italy , The Netherlands',
 'Northwestern Iran , Caucasus',
 'Eastern Islamic Lands',
 'Western Islamic Lands',
 'Central Asia',
 'Egypt, Iraq , Syria',
 'Northwest Turkey',
 'Central Turkey',
 'Sothern Turkmenistan',
 'Uzbekistan , Afghanistan',
 'Uzbekistan And Afghanistan',
 'Northwestern Iran , Turkey',
 'Egypt , Iran',
 'Indiaal',
 'Tunesia , Turkey',
 'Northern , Central India',
 'India , Afghanistan , Iran',
 'Northern , Western India',
 'Iran, Syria , Turkey',
 'Central Asia , Iran',
 'Northern India , Deccan',
 'Western Iran , Northern Iraq',
 'Iraq , Turkey',
 'Egypt , Iraq , Iran',
 'Central India , Sri Lanka',
 'China , Iran',
 'Syria , North Africa',
 'Morocco , Southern Spain',
 'Afghanistan , Iran',
 'India , Sri Lanka',
 'Egypt , Egypt',
 'Afghanistan , Northeastern Iran',
 'Modern Cast Of 39.40.39A',
 'Usa',
 'Egypt (Modern)',
 'Egypt Possibly',
 'U.S.A.',
 'Bohemia',
 'Italy ',
 'Northern Italy',
 'Byzantine Egypt',
 'Europe',
 'Nicomedia',
 'Central Italy',
 'Flanders',
 'Spain  (Setting)',
 'Tirana',
 'Norway',
 'Northern Adriatic',
 'France , Western Europe',
 'France , Netherlands',
 'North France',
 'France , North Spain',
 'North France , South Netherlands',
 'North Africa (Box) , Spain (Lid)',
 'Northern France',
 'Netherlands , France',
 'Germany , The Netherlands',
 'Eastern Mediterranean',
 'South Central France',
 'South France',
 'Sweden',
 'French',
 'Spain , Limoges, France',
 'France ',
 'Northern France , Western Germany',
 'Russian , Northern France',
 'La Tène Ii',
 'Northern France ',
 'Western France',
 'Gaul',
 'Alamania , Northern France',
 'Alamania',
 'Alamania , France',
 'Northern France , Alamania',
 'Niederbreisig',
 'Western Germany',
 'Rhein',
 'Alamania , Northern France , Germany',
 'Northern France , Germany',
 'Germany , Northern France',
 'Southern Germany , Switzerland',
 'South Netherlands',
 'Italian',
 'Scandinavia',
 'Gotland',
 'Central Europe',
 'Egypt , Syria ',
 'England (Possibly)',
 'The Iberian Peninsula (Spain)',
 'Iberian Peninsula',
 'Germany ',
 'Northern Europe',
 'Spain , France',
 'Southern France',
 'Nothern Spain , Southern France',
 'Southwestern France',
 'Belgium',
 'North Africa',
 'Perhaps Syria',
 'German',
 'France (Cartoon) , Southern Netherlands (Woven)',
 'Southern Netherlands (Woven) , France (Cartoon)',
 'Spain Or , Central Italy',
 'French , Belgium',
 'France (Probably)',
 'Byzantium , Spain',
 'Brussels',
 'Austria (Possibly)',
 'North , Central Syria',
 'Southern England',
 'Rome',
 'Italy , Spain',
 'Northern Switzerland',
 'Central , Southern Italian',
 'European',
 'Germany , France',
 'Northern Switzerland ',
 'Austrian',
 'Lake Van Region, Vaspurakan (Now Eastern Turkey)',
 'Syria ',
 'Germany (Present Day France)',
 'Northeastern France',
 'Gaul (France)',
 'Northeast Italy',
 'Spain And Italy',
 'Italy (North)',
 'Ukraine',
 'Black Sea',
 'North Netherlands',
 'North Netherland',
 'Germany , South Germany',
 'Austria (Mounts)',
 'Lower Austria',
 'Germany (France)',
 'Constantinople',
 'South Italy',
 'British Isles',
 'South Netherland',
 'England , Scandinavia',
 'South Netherlandish',
 'France , Spain',
 'France , France',
 'Haute Garonne.',
 'Southern Netherlands',
 'Austria (Now Italy, Trentino-Alto Adige)',
 'England , Meaux, France',
 'Carpathian Basin Region',
 'East-Central Europe',
 'Greece , The Balkans (Possibly)',
 'Bulgaria (Possibly)',
 'Greece , Constantinople',
 'Southern Russia , Black Sea Region ',
 'Scandinavia (Sweden)',
 'France , Southern Netherlands',
 'Crete ',
 'America',
 'Uk',
 'Us',
 'South Africa, Africa',
 'Italy And United States',
 'United Kingdom',
 'China , Mongolia',
 'Japan , China',
 'Tibet',
 'China , Japan',
 'Korea',
 'Myanmar (Formerly Burma)',
 'Thailand',
 'Thailand And Myanmar (Formerly Burma)',
 'Myanmar',
 'Croatia',
 'Spain , Yugoslavia',
 'Ghana , Nigeria',
 'Borneo , China',
 'United States , Mexico: N.A.',
 'Venezuela:N.A.',
 'Iran (Persia)',
 'Russia Federation',
 'Russian Federation',
 'Georgia, Republic Of  [Azerbaijan, Armenia]',
 'Azerbaijan, Armenia , Georgia',
 'Arabia , Iran',
 'Montenegro  Yugoslavia (Former)',
 'Turkey (Old Cat. Arabia)',
 'Arabia',
 'Arabian Peninsula',
 'Syria  Saudia Arabia',
 'Egypt, Bulgaria , Turkey',
 'Bulgaria , Egypt',
 'Former Yugoslavia',
 'Dem. Rep. Of Congo',
 'Congo',
 'Mozambique',
 'Senegal , Gambia',
 'Benin , Gabon',
 'Benin',
 'Republic Of Cameroon',
 'Canada: N.A.',
 'Guyana',
 'Guatemala , Guyana',
 'United States , Brazil',
 'New Guinea (Phillipine)',
 'Marshall Islands',
 'Sarawak',
 'Romania',
 'United Kingdom , Germany',
 'Slovakia',
 'Germany, France, , Bohemia',
 'United States , Germany ',
 'Austria , Germany',
 'Finland',
 'Friesland',
 'Germany , Switzerland',
 'Arabia , North Africa',
 'Uganda , Kenya',
 'Republic Of Cameroon , Gabon',
 'Italy , Germany',
 'Norfolk Island',
 'Turkey , Greece',
 'Italy , Sicily',
 'Sulawesi (Celebes)',
 'Czech Republic (Bohemia)',
 'Germany , England',
 'Egypt (British Repro)',
 'Uganda/Tanzania',
 'Mozambique , Zimbabwe , Malawi',
 'France , Belgium',
 'Peru , Peru',
 "Liberia-Côte D'Ivoire (Ivory Coast) Border",
 'United States , Canada: N.A.',
 'Germany , Belgium',
 'Bosnia And Herzegovina (Former Yugoslavia)',
 'Iran (Persia) And Turkey',
 'Nigeria , Benin',
 'Gambia',
 'Montenegro',
 'Japan , Korea',
 'Uganda/Rwanda',
 'Malta',
 'Republic Of Costa Rica',
 'United States , Mexico',
 'Colombia , Costa Rica',
 'Nepal',
 'France:N.',
 'China , Korea',
 'Burkina Faso (Formerly Upper Volta)',
 'Ivory Coast',
 'Sumatra',
 'Ghana , Senegal',
 'Nigeria , Congo',
 'Lesotho',
 'Tajikistan',
 'Czechoslovakia , Germany',
 'United Kingdom , France',
 'Nigeria, Ghana , Sierra Leone',
 'Serbia',
 'Ireland , United Kingdom',
 'Nigeria , Cameroon',
 'Mongolia',
 'France/Usa',
 'France , United States',
 'Flemish',
 'Republic Of Guinea',
 'Uzbekistan , Tajikistan',
 'Malawi , Tanzania',
 'Tibet , China , India',
 'Cambodia',
 'Colombia , Venezuela',
 'Hungary , Slovenia',
 'Austria / Germany',
 'Germany (Probably)',
 'Mauritania',
 'Republic Of  Cameroon',
 'Kosova',
 'Tibet/North India',
 'Bhutan',
 'Germany , Austria',
 'Denmark',
 'Croatia (Former Yugoslavia)',
 'Zambia , Zimbabwe',
 'United States , Austria',
 'Uganda-Sudan',
 'Burma',
 'Uganda , Democratic Republic Of Congo',
 'Tanzania/Kenya',
 'Macedonia',
 'Slovenia',
 'Republic Of Congo & Angola',
 'Philippine Islands',
 'Macedonia (Former Yugoslavia)',
 'United Kingdom ',
 'Republic Of The Philippines',
 'Norway , Sweden',
 'England , Germany',
 'Germany , Poland',
 'India (North)',
 'Netherlands , Belgium',
 'Myanmar (Burma)',
 'Bulgaria , Switzerland',
 'Myanmar (Burmah) , Thai',
 'Sulawesi',
 'Tibet , China',
 'Serbia (Former Yugoslavia)',
 'Bosnia (Former Yugoslavia)',
 'Herzegovina (Former Yugoslavia)',
 'Bosnia - Herzegovina (Former Yugoslavia)',
 'Scandinavia , Austria',
 'Ireland ',
 'Austria ',
 'Belgium ',
 'Dem. Rep. Congo',
 'Turkey , Azerbaijan',
 'Bohemia , Germany , Italy',
 'Bohemia (Hungary)',
 'Laos And Thailand',
 'Persia , Turkey',
 'Tibet/Nepal',
 'Myanmar (Burma) , Thailand',
 'Switzerland , France',
 'Republic Of Madagascar',
 'Mali , Algeria/Tunesia',
 'Ethiopia , Sudan',
 'Pakistan , India',
 'Czech Republic , Slovakia',
 'Italy , United Kingdom',
 'Turkey , India',
 'Canaan',
 'Cyprus',
 'Egypt , Levant',
 'Egypt , Italy',
 'Egypt (Or Italy , Turkey)',
 'Egypt , Gaul',
 'Nubia (Sudan)',
 'Surinam',
 'Burkina Faso ',
 'India (Golconda , Bidar)',
 'Russia , United States',
 'India , United States',
 'Southwestern Iran',
 'Northwestern Iran , Azerbaijan',
 'Caucasus',
 'Southern Turkey',
 'Northern Iraq',
 'Iran , Europe',
 'Belize, Honduras, Guatemala, , Mexico',
 'Central Mexico',
 'United States , United States , Canada',
 'Canada , Canada',
 'Turkey , Central Asia',
 'Bolivia, Peru, , Chile',
 'Italy , Italy',
 'Canada , United States , United States',
 'Argentina, Peru, , Bolivia',
 'New Spain (Mexico)',
 'Tunisia (Probably)',
 'Iran And Turkey',
 'Western Australia',
 'Southwest Iran',
 'Kirghiztan',
 'Northwest Iran',
 'Iran , India; Assembled , Refurbished In Rome',
 'South Africa , Zimbabwe',
 'Uruguay',
 'Nigeria , Chad',
 'North India , Deccan',
 'Martinique',
 'Iraq , China',
 'United States Of America']

###c) Forward and backward fill:

In [37]:
df = df.sort_values('Title')
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,New_Dimensions,hight_col,width_col,length_col,New_Country
94228,2009.300.6020,False,False,False,170212,NaN,Costume Institute,2009.0,Belt,"""Diana""",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91660,2009.300.590,False,False,False,159137,NaN,Costume Institute,2009.0,Dinner dress,"""Spiral""",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181683,1994.264.32.79,False,False,False,290077,NaN,Photographs,1994.0,Postcard,"Cadillac Square, Detroit, Mich.",...,NaN,"Metropolitan Museum of Art, New York, NY",Buildings,http://vocab.getty.edu/page/aat/300004789,https://www.wikidata.org/wiki/Q41176,3 9/16 5 1/2 in.,NaN,NaN,NaN,NaN
448078,2018.62.33,False,False,True,770958,516.0,European Sculpture and Decorative Arts,2018.0,Ewer,Ewer,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,"22.1 × 15.9 × 16.2 , 750g",NaN,NaN,NaN,NaN
455561,63.350.651.89,False,False,False,780621,NaN,Photographs,1963.0,Stereograph,"Interior of St. Peter's, Rome, Showing the Gr...",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,8.9 × 17.8,8.9,NaN,17.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477466,2021.343,False,False,True,856957,NaN,Asian Art,2021,Drawing,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,folded,NaN,NaN,NaN,NaN
477467,2021.344,False,False,True,856958,NaN,Asian Art,2021,Drawing,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,folded,NaN,NaN,NaN,NaN
477483,2021.424,False,False,False,857029,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,45 × 28.3,45.0,NaN,28.3,NaN
477484,2021.425,False,False,False,857030,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,45 × 27.8,45.0,NaN,27.8,NaN
477485,2021.423,False,False,False,857031,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,46 × 28.1,46.0,NaN,28.1,NaN

In [38]:
df['Title']

94228                                               "Diana"
91660                                              "Spiral"
181683                      Cadillac Square, Detroit, Mich.
448078                                                 Ewer
455561     Interior of St. Peter's, Rome, Showing the Gr...
                                ...
477466                                                  NaN
477467                                                  NaN
477483                                                  NaN
477484                                                  NaN
477485                                                  NaN
Name: Title, Length: 477804, dtype: object

In [39]:
df['Constituent ID'] = df.groupby('Title')['Constituent ID'].fillna(method='bfill').fillna(method='ffill')

In [40]:
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,New_Dimensions,hight_col,width_col,length_col,New_Country
94228,2009.300.6020,False,False,False,170212,NaN,Costume Institute,2009.0,Belt,"""Diana""",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91660,2009.300.590,False,False,False,159137,NaN,Costume Institute,2009.0,Dinner dress,"""Spiral""",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181683,1994.264.32.79,False,False,False,290077,NaN,Photographs,1994.0,Postcard,"Cadillac Square, Detroit, Mich.",...,NaN,"Metropolitan Museum of Art, New York, NY",Buildings,http://vocab.getty.edu/page/aat/300004789,https://www.wikidata.org/wiki/Q41176,3 9/16 5 1/2 in.,NaN,NaN,NaN,NaN
448078,2018.62.33,False,False,True,770958,516.0,European Sculpture and Decorative Arts,2018.0,Ewer,Ewer,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,"22.1 × 15.9 × 16.2 , 750g",NaN,NaN,NaN,NaN
455561,63.350.651.89,False,False,False,780621,NaN,Photographs,1963.0,Stereograph,"Interior of St. Peter's, Rome, Showing the Gr...",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,8.9 × 17.8,8.9,NaN,17.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477466,2021.343,False,False,True,856957,NaN,Asian Art,2021,Drawing,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,folded,NaN,NaN,NaN,NaN
477467,2021.344,False,False,True,856958,NaN,Asian Art,2021,Drawing,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,folded,NaN,NaN,NaN,NaN
477483,2021.424,False,False,False,857029,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,45 × 28.3,45.0,NaN,28.3,NaN
477484,2021.425,False,False,False,857030,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,45 × 27.8,45.0,NaN,27.8,NaN
477485,2021.423,False,False,False,857031,NaN,Asian Art,2021,Painting,NaN,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,46 × 28.1,46.0,NaN,28.1,NaN

In [41]:
df = df.sort_index()
df

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,New_Dimensions,hight_col,width_col,length_col,New_Country
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1.7,1.7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477799,23.112.2893,False,False,True,860869,NaN,Drawings and Prints,1923,Drawing,Phaeton #24567,...,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,34.3 × 57.2,34.3,NaN,57.2,NaN
477800,23.112.2894,False,False,True,860870,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton #25538-25539 (#21222),...,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33.0,NaN,56.5,NaN
477801,53.600.1434,False,False,False,860871,NaN,Drawings and Prints,1953,Print,"Forest landscape with cattle drinking, a woman...",...,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,29.6 × 19.4,29.6,NaN,19.4,NaN
477802,23.112.2895,False,False,True,860872,NaN,Drawings and Prints,1923,Drawing,Phaeton with folding top,...,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,33 × 56.5,33.0,NaN,56.5,NaN
477803,23.112.2896,False,False,True,860873,NaN,Drawings and Prints,1923,Drawing,Stanhope Phaeton,...,NaN,"Metropolitan Museum of Art, New York, NY",Carriages,http://vocab.getty.edu/page/aat/300185335,https://www.wikidata.org/wiki/Q235356,29.8 × 45.1,29.8,NaN,45.1,NaN

#Aggregation

###a) Get the number of artworks per individual country

In [42]:
exploded_data = df.explode('New_Country')

In [43]:
artworks_per_country = exploded_data['New_Country'].value_counts().reset_index()
artworks_per_country.columns = ['country', 'artwork_count']

artworks_per_country

                     country  artwork_count
0                      Egypt          31376
1              United States           9119
2                       Iran           6331
3                       Peru           3399
4                     France           1934
..                       ...            ...
754  France , Western Europe              1
755        Northern Adriatic              1
756                   Tirana              1
757         Spain  (Setting)              1
758       Northwestern India              1

[759 rows x 2 columns]

###b)Get the number of artists per country

In [44]:
artists_per_country =exploded_data.groupby('New_Country')['Artist Display Name'].nunique().reset_index()
artists_per_country.columns = ['country', 'artist_count']
artists_per_country

                             country  artist_count
0                        Afghanistan            24
1         Afghanistan , Central Asia             0
2                 Afghanistan , Iran             0
3                Afghanistan , Italy             0
4    Afghanistan , Northeastern Iran             0
..                               ...           ...
754                Zambia , Zimbabwe             0
755                         Zanzibar             0
756                         Zimbabwe             0
757            Zimbabwe , Mozambique             0
758                             null             0

[759 rows x 2 columns]

In [45]:
df.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL', 'New_Dimensions', 'hight_col', 'width_col',
       'length_col', 'New_Country'],
      dtype='object')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 477804 entries, 0 to 477803
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Object Number            477804 non-null  object
 1   Is Highlight             477804 non-null  bool
 2   Is Timeline Work         477804 non-null  bool
 3   Is Public Domain         477804 non-null  bool
 4   Object ID                477804 non-null  int64
 5   Gallery Number           51776 non-null   object
 6   Department               477804 non-null  object
 7   AccessionYear            474248 non-null  object
 8   Object Name              476113 non-null  object
 9   Title                    448619 non-null  object
 10  Culture                  207379 non-null  object
 11  Period                   90956 non-null   object
 12  Dynasty                  23233 non-null   object
 13  Reign                    11226 non-null   object
 14  Portfolio                23530 non-null   object
 15  Constituent ID           477804 non-null  object
 16  Artist Role              273436 non-null  object
 17  Artist Prefix            275535 non-null  object
 18  Artist Display Name      275535 non-null  object
 19  Artist Display Bio       273436 non-null  object
 20  Artist Suffix            275487 non-null  object
 21  Artist Alpha Sort        275535 non-null  object
 22  Artist Nationality       275535 non-null  object
 23  Artist Begin Date        275535 non-null  object
 24  Artist End Date          275535 non-null  object
 25  Artist Gender            103061 non-null  object
 26  Artist ULAN URL          222021 non-null  object
 27  Artist Wikidata URL      217732 non-null  object
 28  Object Date              463937 non-null  object
 29  Object Begin Date        477804 non-null  int64
 30  Object End Date          477804 non-null  int64
 31  Medium                   470684 non-null  object
 32  Dimensions               402510 non-null  object
 33  Credit Line              477353 non-null  object
 34  Geography Type           59769 non-null   object
 35  City                     32407 non-null   object
 36  State                    2550 non-null    object
 37  County                   8450 non-null    object
 38  Country                  75751 non-null   object
 39  Region                   31360 non-null   object
 40  Subregion                22124 non-null   object
 41  Locale                   15709 non-null   object
 42  Locus                    7493 non-null    object
 43  Excavation               16558 non-null   object
 44  River                    2095 non-null    object
 45  Classification           399598 non-null  object
 46  Rights and Reproduction  24198 non-null   object
 47  Link Resource            477804 non-null  object
 48  Object Wikidata URL      22265 non-null   object
 49  Metadata Date            0 non-null       float64
 50  Repository               477804 non-null  object
 51  Tags                     200400 non-null  object
 52  Tags AAT URL             200400 non-null  object
 53  Tags Wikidata URL        200400 non-null  object
 54  New_Dimensions           381466 non-null  object
 55  hight_col                325339 non-null  float64
 56  width_col                128919 non-null  float64
 57  length_col               128860 non-null  float64
 58  New_Country              75751 non-null   object
dtypes: bool(3), float64(4), int64(3), object(49)
memory usage: 209.2+ MB

###c)Average height, width, and length per country

In [47]:
df['New_Country'] = df['New_Country'].astype(str)
df['hight_col'] = pd.to_numeric(df['hight_col'], errors='coerce')
df['width_col'] = pd.to_numeric(df['width_col'], errors='coerce')
df['length_col'] = pd.to_numeric(df['length_col'], errors='coerce')




df.groupby('New_Country')[['hight_col', 'width_col','length_col']].mean()

                                 hight_col  width_col  length_col
New_Country
Afghanistan                      38.945545   4.100000    4.050000
Afghanistan , Central Asia       15.900000        NaN         NaN
Afghanistan , Iran               12.400000        NaN         NaN
Afghanistan , Italy                    NaN        NaN         NaN
Afghanistan , Northeastern Iran  10.950000        NaN         NaN
...                                    ...        ...         ...
Zanzibar                         12.700000        NaN         NaN
Zimbabwe                         12.325000  11.300000   11.275000
Zimbabwe , Mozambique            14.000000  22.200000    9.500000
nan                              29.606746  28.705735   22.507534
null                             36.040000  32.366667         NaN

[760 rows x 3 columns]

###d)Collect a unique list of constituent ids per country

In [48]:
unique_ids_per_country = df.groupby('New_Country')['Constituent ID'].unique().reset_index()
unique_ids_per_country

,New_Country,Constituent ID
0,Afghanistan,"[291512244, 2346, 16413, 12916, 2927, 20241252..."
1,"Afghanistan , Central Asia",[13048]
2,"Afghanistan , Iran",[18209]
3,"Afghanistan , Italy",[18209]
4,"Afghanistan , Northeastern Iran","[351713892, 3822]"
...,...,...
755,Zanzibar,[16315]
756,Zimbabwe,"[16998616171, 15525, 954]"
757,"Zimbabwe , Mozambique",[16998616171]
758,nan,"[16429, 107, 14546614719, 108, 16533, 937, 165..."
759,null,"[2016, 10218716272, 13271, 16237]"

#Storage

#The resulting tables have to be stored in an appropriate format, for example storing the data in a relational database or CSV. You must describe why you chose the storage format you have chosen (How/why is this format helpful, what are the advantages/disadvantages)

I will choose Relational Database:








Useful: Storing data in a relational database allows for a more structured and organised approach of storing and managing data. It enables efficient querying, indexing, and the maintenance of relationships between tables.

Advantages:

1)Data Integrity: Through limitations such as primary keys, foreign keys, and data types, relational databases ensure data accuracy and consistency.

2)Scalability: Relational databases are built to manage enormous datasets and allow several users to access them at the same time.


3)SQL (Structured Query Language) allows for complicated searches, aggregations, and join operations on data, making it simple to extract significant insights.


Disadvantages:

1)Complexity: Setting up and managing a relational database involves technical knowledge as well as administrative abilities.

2)Cost: Depending on the database system, there may be licensing or infrastructure costs associated with using a relational database.

#Optimization

#Imagine that the volume of the data has become very large and that we’re working with multiple data sources and tables, the data pipeline is starting to take longer and longer to complete and we need to optimize it. Without implementing any code, explain what approaches you would take to optimize the performance of a data pipeline.

1) Use Distributed Computing

Distributed computing is one of the most effective methods for accelerating your data flow. This comprises breaking down data processing into smaller components that can be handled simultaneously by many machines. This allows you to process more data in less time by drastically lowering processing time and increasing throughput.

2) Choose the Correct Data Storage

The storage technology you choose may have a considerable impact on the performance of your pipeline. Data size, processing requirements, and budget are all important considerations. If you're dealing with large amounts of structured data, a relational database can be a good option. If you're working with unstructured data, a NoSQL database may be more appropriate. As a result, if you need to strike a balance between performance and cost, a cloud-based storage solution like Amazon S3 may be the ideal alternative.

3) Optimize Data Compression

Data compression is also required to increase the efficiency of your data pipeline. By compressing your data, you can reduce its size and thus its storage and processing costs. This can help save processing time when only a little amount of data needs to be carried through the pipeline. However, compression must be calibrated with data quality and processing requirements, since too much compression may have a negative impact on performance.Price and performance must be balanced.

4) Data Quality and Governance

Data quality and governance are essential components of an effective data pipeline. Data quality refers to the accuracy, completeness, and consistency of data being processed, and is critical to ensuring that data pipeline outputs are usable and valuable.